/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.6.0-dev.20260912.110338Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AccountApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountApiKey{}

// AccountApiKey struct for AccountApiKey
type AccountApiKey struct {
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	Account     string     `json:"account"`
	Enabled     bool       `json:"enabled"`
	MaskedValue *string    `json:"maskedValue,omitempty"`
	CreatedBy   string     `json:"created_by"`
	UpdatedBy   string     `json:"updated_by"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	Scope       string     `json:"scope"`
	Profile     string     `json:"profile"`
	LastUsedAt  *time.Time `json:"last_used_at,omitempty"`
}

type _AccountApiKey AccountApiKey

// NewAccountApiKey instantiates a new AccountApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountApiKey(id string, name string, account string, enabled bool, createdBy string, updatedBy string, createdAt time.Time, updatedAt time.Time, scope string, profile string) *AccountApiKey {
	this := AccountApiKey{}
	this.Id = id
	this.Name = name
	this.Account = account
	this.Enabled = enabled
	this.CreatedBy = createdBy
	this.UpdatedBy = updatedBy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Scope = scope
	this.Profile = profile
	return &this
}

// NewAccountApiKeyWithDefaults instantiates a new AccountApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountApiKeyWithDefaults() *AccountApiKey {
	this := AccountApiKey{}
	return &this
}

// GetId returns the Id field value
func (o *AccountApiKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccountApiKey) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AccountApiKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccountApiKey) SetName(v string) {
	o.Name = v
}

// GetAccount returns the Account field value
func (o *AccountApiKey) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *AccountApiKey) SetAccount(v string) {
	o.Account = v
}

// GetEnabled returns the Enabled field value
func (o *AccountApiKey) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AccountApiKey) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMaskedValue returns the MaskedValue field value if set, zero value otherwise.
func (o *AccountApiKey) GetMaskedValue() string {
	if o == nil || IsNil(o.MaskedValue) {
		var ret string
		return ret
	}
	return *o.MaskedValue
}

// GetMaskedValueOk returns a tuple with the MaskedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetMaskedValueOk() (*string, bool) {
	if o == nil || IsNil(o.MaskedValue) {
		return nil, false
	}
	return o.MaskedValue, true
}

// HasMaskedValue returns a boolean if a field has been set.
func (o *AccountApiKey) HasMaskedValue() bool {
	if o != nil && !IsNil(o.MaskedValue) {
		return true
	}

	return false
}

// SetMaskedValue gets a reference to the given string and assigns it to the MaskedValue field.
func (o *AccountApiKey) SetMaskedValue(v string) {
	o.MaskedValue = &v
}

// GetCreatedBy returns the CreatedBy field value
func (o *AccountApiKey) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *AccountApiKey) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetUpdatedBy returns the UpdatedBy field value
func (o *AccountApiKey) GetUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// SetUpdatedBy sets field value
func (o *AccountApiKey) SetUpdatedBy(v string) {
	o.UpdatedBy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccountApiKey) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccountApiKey) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AccountApiKey) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AccountApiKey) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *AccountApiKey) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *AccountApiKey) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *AccountApiKey) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetScope returns the Scope field value
func (o *AccountApiKey) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *AccountApiKey) SetScope(v string) {
	o.Scope = v
}

// GetProfile returns the Profile field value
func (o *AccountApiKey) GetProfile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Profile, true
}

// SetProfile sets field value
func (o *AccountApiKey) SetProfile(v string) {
	o.Profile = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *AccountApiKey) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountApiKey) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *AccountApiKey) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given time.Time and assigns it to the LastUsedAt field.
func (o *AccountApiKey) SetLastUsedAt(v time.Time) {
	o.LastUsedAt = &v
}

func (o AccountApiKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["account"] = o.Account
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.MaskedValue) {
		toSerialize["maskedValue"] = o.MaskedValue
	}
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["updated_by"] = o.UpdatedBy
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	toSerialize["scope"] = o.Scope
	toSerialize["profile"] = o.Profile
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	return toSerialize, nil
}

func (o *AccountApiKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"account",
		"enabled",
		"created_by",
		"updated_by",
		"created_at",
		"updated_at",
		"scope",
		"profile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountApiKey := _AccountApiKey{}

	err = json.Unmarshal(data, &varAccountApiKey)

	if err != nil {
		return err
	}

	*o = AccountApiKey(varAccountApiKey)

	return err
}

type NullableAccountApiKey struct {
	value *AccountApiKey
	isSet bool
}

func (v NullableAccountApiKey) Get() *AccountApiKey {
	return v.value
}

func (v *NullableAccountApiKey) Set(val *AccountApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountApiKey(val *AccountApiKey) *NullableAccountApiKey {
	return &NullableAccountApiKey{value: val, isSet: true}
}

func (v NullableAccountApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
