/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OAuthGrantStatus the model 'OAuthGrantStatus'
type OAuthGrantStatus string

// List of OAuthGrantStatus
const (
	OAUTHGRANTSTATUS_ACTIVE                   OAuthGrantStatus = "active"
	OAUTHGRANTSTATUS_REVOKED                  OAuthGrantStatus = "revoked"
	OAUTHGRANTSTATUS_EXPIRED                  OAuthGrantStatus = "expired"
	OAUTHGRANTSTATUS_UNKNOWN_DEFAULT_OPEN_API OAuthGrantStatus = "unknown_default_open_api"
)

// All allowed values of OAuthGrantStatus enum
var AllowedOAuthGrantStatusEnumValues = []OAuthGrantStatus{
	"active",
	"revoked",
	"expired",
	"unknown_default_open_api",
}

func (v *OAuthGrantStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OAuthGrantStatus(value)
	for _, existing := range AllowedOAuthGrantStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = OAUTHGRANTSTATUS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewOAuthGrantStatusFromValue returns a pointer to a valid OAuthGrantStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOAuthGrantStatusFromValue(v string) (*OAuthGrantStatus, error) {
	ev := OAuthGrantStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OAuthGrantStatus: valid values are %v", v, AllowedOAuthGrantStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OAuthGrantStatus) IsValid() bool {
	for _, existing := range AllowedOAuthGrantStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OAuthGrantStatus value
func (v OAuthGrantStatus) Ptr() *OAuthGrantStatus {
	return &v
}

type NullableOAuthGrantStatus struct {
	value *OAuthGrantStatus
	isSet bool
}

func (v NullableOAuthGrantStatus) Get() *OAuthGrantStatus {
	return v.value
}

func (v *NullableOAuthGrantStatus) Set(val *OAuthGrantStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthGrantStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthGrantStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthGrantStatus(val *OAuthGrantStatus) *NullableOAuthGrantStatus {
	return &NullableOAuthGrantStatus{value: val, isSet: true}
}

func (v NullableOAuthGrantStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthGrantStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
