/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DriftAnalysisProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriftAnalysisProgress{}

// DriftAnalysisProgress struct for DriftAnalysisProgress
type DriftAnalysisProgress struct {
	Total                     float32         `json:"total"`
	Processed                 float32         `json:"processed"`
	Missing                   float32         `json:"missing"`
	Stale                     float32         `json:"stale"`
	Status                    string          `json:"status"`
	CurrentBatch              float32         `json:"current_batch"`
	TotalBatches              float32         `json:"total_batches"`
	PercentComplete           float32         `json:"percent_complete"`
	DocsPerSecond             float32         `json:"docs_per_second"`
	ElapsedSeconds            float32         `json:"elapsed_seconds"`
	EstimatedSecondsRemaining NullableFloat32 `json:"estimated_seconds_remaining"`
}

type _DriftAnalysisProgress DriftAnalysisProgress

// NewDriftAnalysisProgress instantiates a new DriftAnalysisProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriftAnalysisProgress(total float32, processed float32, missing float32, stale float32, status string, currentBatch float32, totalBatches float32, percentComplete float32, docsPerSecond float32, elapsedSeconds float32, estimatedSecondsRemaining NullableFloat32) *DriftAnalysisProgress {
	this := DriftAnalysisProgress{}
	this.Total = total
	this.Processed = processed
	this.Missing = missing
	this.Stale = stale
	this.Status = status
	this.CurrentBatch = currentBatch
	this.TotalBatches = totalBatches
	this.PercentComplete = percentComplete
	this.DocsPerSecond = docsPerSecond
	this.ElapsedSeconds = elapsedSeconds
	this.EstimatedSecondsRemaining = estimatedSecondsRemaining
	return &this
}

// NewDriftAnalysisProgressWithDefaults instantiates a new DriftAnalysisProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriftAnalysisProgressWithDefaults() *DriftAnalysisProgress {
	this := DriftAnalysisProgress{}
	return &this
}

// GetTotal returns the Total field value
func (o *DriftAnalysisProgress) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *DriftAnalysisProgress) SetTotal(v float32) {
	o.Total = v
}

// GetProcessed returns the Processed field value
func (o *DriftAnalysisProgress) GetProcessed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Processed
}

// GetProcessedOk returns a tuple with the Processed field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetProcessedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Processed, true
}

// SetProcessed sets field value
func (o *DriftAnalysisProgress) SetProcessed(v float32) {
	o.Processed = v
}

// GetMissing returns the Missing field value
func (o *DriftAnalysisProgress) GetMissing() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Missing
}

// GetMissingOk returns a tuple with the Missing field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetMissingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Missing, true
}

// SetMissing sets field value
func (o *DriftAnalysisProgress) SetMissing(v float32) {
	o.Missing = v
}

// GetStale returns the Stale field value
func (o *DriftAnalysisProgress) GetStale() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Stale
}

// GetStaleOk returns a tuple with the Stale field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetStaleOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stale, true
}

// SetStale sets field value
func (o *DriftAnalysisProgress) SetStale(v float32) {
	o.Stale = v
}

// GetStatus returns the Status field value
func (o *DriftAnalysisProgress) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DriftAnalysisProgress) SetStatus(v string) {
	o.Status = v
}

// GetCurrentBatch returns the CurrentBatch field value
func (o *DriftAnalysisProgress) GetCurrentBatch() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentBatch
}

// GetCurrentBatchOk returns a tuple with the CurrentBatch field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetCurrentBatchOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentBatch, true
}

// SetCurrentBatch sets field value
func (o *DriftAnalysisProgress) SetCurrentBatch(v float32) {
	o.CurrentBatch = v
}

// GetTotalBatches returns the TotalBatches field value
func (o *DriftAnalysisProgress) GetTotalBatches() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalBatches
}

// GetTotalBatchesOk returns a tuple with the TotalBatches field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetTotalBatchesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalBatches, true
}

// SetTotalBatches sets field value
func (o *DriftAnalysisProgress) SetTotalBatches(v float32) {
	o.TotalBatches = v
}

// GetPercentComplete returns the PercentComplete field value
func (o *DriftAnalysisProgress) GetPercentComplete() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PercentComplete
}

// GetPercentCompleteOk returns a tuple with the PercentComplete field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetPercentCompleteOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PercentComplete, true
}

// SetPercentComplete sets field value
func (o *DriftAnalysisProgress) SetPercentComplete(v float32) {
	o.PercentComplete = v
}

// GetDocsPerSecond returns the DocsPerSecond field value
func (o *DriftAnalysisProgress) GetDocsPerSecond() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DocsPerSecond
}

// GetDocsPerSecondOk returns a tuple with the DocsPerSecond field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetDocsPerSecondOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocsPerSecond, true
}

// SetDocsPerSecond sets field value
func (o *DriftAnalysisProgress) SetDocsPerSecond(v float32) {
	o.DocsPerSecond = v
}

// GetElapsedSeconds returns the ElapsedSeconds field value
func (o *DriftAnalysisProgress) GetElapsedSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ElapsedSeconds
}

// GetElapsedSecondsOk returns a tuple with the ElapsedSeconds field value
// and a boolean to check if the value has been set.
func (o *DriftAnalysisProgress) GetElapsedSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ElapsedSeconds, true
}

// SetElapsedSeconds sets field value
func (o *DriftAnalysisProgress) SetElapsedSeconds(v float32) {
	o.ElapsedSeconds = v
}

// GetEstimatedSecondsRemaining returns the EstimatedSecondsRemaining field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *DriftAnalysisProgress) GetEstimatedSecondsRemaining() float32 {
	if o == nil || o.EstimatedSecondsRemaining.Get() == nil {
		var ret float32
		return ret
	}

	return *o.EstimatedSecondsRemaining.Get()
}

// GetEstimatedSecondsRemainingOk returns a tuple with the EstimatedSecondsRemaining field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriftAnalysisProgress) GetEstimatedSecondsRemainingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedSecondsRemaining.Get(), o.EstimatedSecondsRemaining.IsSet()
}

// SetEstimatedSecondsRemaining sets field value
func (o *DriftAnalysisProgress) SetEstimatedSecondsRemaining(v float32) {
	o.EstimatedSecondsRemaining.Set(&v)
}

func (o DriftAnalysisProgress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriftAnalysisProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["processed"] = o.Processed
	toSerialize["missing"] = o.Missing
	toSerialize["stale"] = o.Stale
	toSerialize["status"] = o.Status
	toSerialize["current_batch"] = o.CurrentBatch
	toSerialize["total_batches"] = o.TotalBatches
	toSerialize["percent_complete"] = o.PercentComplete
	toSerialize["docs_per_second"] = o.DocsPerSecond
	toSerialize["elapsed_seconds"] = o.ElapsedSeconds
	toSerialize["estimated_seconds_remaining"] = o.EstimatedSecondsRemaining.Get()
	return toSerialize, nil
}

func (o *DriftAnalysisProgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"processed",
		"missing",
		"stale",
		"status",
		"current_batch",
		"total_batches",
		"percent_complete",
		"docs_per_second",
		"elapsed_seconds",
		"estimated_seconds_remaining",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDriftAnalysisProgress := _DriftAnalysisProgress{}

	err = json.Unmarshal(data, &varDriftAnalysisProgress)

	if err != nil {
		return err
	}

	*o = DriftAnalysisProgress(varDriftAnalysisProgress)

	return err
}

type NullableDriftAnalysisProgress struct {
	value *DriftAnalysisProgress
	isSet bool
}

func (v NullableDriftAnalysisProgress) Get() *DriftAnalysisProgress {
	return v.value
}

func (v *NullableDriftAnalysisProgress) Set(val *DriftAnalysisProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableDriftAnalysisProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableDriftAnalysisProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriftAnalysisProgress(val *DriftAnalysisProgress) *NullableDriftAnalysisProgress {
	return &NullableDriftAnalysisProgress{value: val, isSet: true}
}

func (v NullableDriftAnalysisProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriftAnalysisProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
