/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComputedFacetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputedFacetResponse{}

// ComputedFacetResponse struct for ComputedFacetResponse
type ComputedFacetResponse struct {
	Total                *float32 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ComputedFacetResponse ComputedFacetResponse

// NewComputedFacetResponse instantiates a new ComputedFacetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputedFacetResponse() *ComputedFacetResponse {
	this := ComputedFacetResponse{}
	return &this
}

// NewComputedFacetResponseWithDefaults instantiates a new ComputedFacetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputedFacetResponseWithDefaults() *ComputedFacetResponse {
	this := ComputedFacetResponse{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ComputedFacetResponse) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputedFacetResponse) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ComputedFacetResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *ComputedFacetResponse) SetTotal(v float32) {
	o.Total = &v
}

func (o ComputedFacetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputedFacetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ComputedFacetResponse) UnmarshalJSON(data []byte) (err error) {
	varComputedFacetResponse := _ComputedFacetResponse{}

	err = json.Unmarshal(data, &varComputedFacetResponse)

	if err != nil {
		return err
	}

	*o = ComputedFacetResponse(varComputedFacetResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableComputedFacetResponse struct {
	value *ComputedFacetResponse
	isSet bool
}

func (v NullableComputedFacetResponse) Get() *ComputedFacetResponse {
	return v.value
}

func (v *NullableComputedFacetResponse) Set(val *ComputedFacetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComputedFacetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComputedFacetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputedFacetResponse(val *ComputedFacetResponse) *NullableComputedFacetResponse {
	return &NullableComputedFacetResponse{value: val, isSet: true}
}

func (v NullableComputedFacetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputedFacetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
