/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DataStoreTableDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataStoreTableDetail{}

// DataStoreTableDetail struct for DataStoreTableDetail
type DataStoreTableDetail struct {
	// Table name (must be valid SQL identifier)
	Name string `json:"name"`
	// Human-readable description
	Description *string `json:"description,omitempty"`
	// Column definitions
	Columns []DataColumn `json:"columns"`
	// Foreign key constraints
	ForeignKeys []DataForeignKey `json:"foreign_keys,omitempty"`
	// Index definitions
	Indexes []DataIndex `json:"indexes,omitempty"`
	// Semantic categorization for AI understanding
	SemanticType *DataTableSemanticType `json:"semantic_type,omitempty"`
	// Tags for organization
	Tags []string `json:"tags"`
	// Current row count (updated after imports)
	RowCount *float32 `json:"row_count,omitempty"`
	// Table creation timestamp
	CreatedAt *string `json:"created_at,omitempty"`
	// Last modification timestamp
	UpdatedAt  *string                  `json:"updated_at,omitempty"`
	SampleData []map[string]interface{} `json:"sample_data,omitempty"`
}

type _DataStoreTableDetail DataStoreTableDetail

// NewDataStoreTableDetail instantiates a new DataStoreTableDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataStoreTableDetail(name string, columns []DataColumn, tags []string) *DataStoreTableDetail {
	this := DataStoreTableDetail{}
	this.Name = name
	this.Columns = columns
	this.Tags = tags
	return &this
}

// NewDataStoreTableDetailWithDefaults instantiates a new DataStoreTableDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataStoreTableDetailWithDefaults() *DataStoreTableDetail {
	this := DataStoreTableDetail{}
	return &this
}

// GetName returns the Name field value
func (o *DataStoreTableDetail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataStoreTableDetail) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DataStoreTableDetail) SetDescription(v string) {
	o.Description = &v
}

// GetColumns returns the Columns field value
func (o *DataStoreTableDetail) GetColumns() []DataColumn {
	if o == nil {
		var ret []DataColumn
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetColumnsOk() ([]DataColumn, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *DataStoreTableDetail) SetColumns(v []DataColumn) {
	o.Columns = v
}

// GetForeignKeys returns the ForeignKeys field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetForeignKeys() []DataForeignKey {
	if o == nil || IsNil(o.ForeignKeys) {
		var ret []DataForeignKey
		return ret
	}
	return o.ForeignKeys
}

// GetForeignKeysOk returns a tuple with the ForeignKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetForeignKeysOk() ([]DataForeignKey, bool) {
	if o == nil || IsNil(o.ForeignKeys) {
		return nil, false
	}
	return o.ForeignKeys, true
}

// HasForeignKeys returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasForeignKeys() bool {
	if o != nil && !IsNil(o.ForeignKeys) {
		return true
	}

	return false
}

// SetForeignKeys gets a reference to the given []DataForeignKey and assigns it to the ForeignKeys field.
func (o *DataStoreTableDetail) SetForeignKeys(v []DataForeignKey) {
	o.ForeignKeys = v
}

// GetIndexes returns the Indexes field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetIndexes() []DataIndex {
	if o == nil || IsNil(o.Indexes) {
		var ret []DataIndex
		return ret
	}
	return o.Indexes
}

// GetIndexesOk returns a tuple with the Indexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetIndexesOk() ([]DataIndex, bool) {
	if o == nil || IsNil(o.Indexes) {
		return nil, false
	}
	return o.Indexes, true
}

// HasIndexes returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasIndexes() bool {
	if o != nil && !IsNil(o.Indexes) {
		return true
	}

	return false
}

// SetIndexes gets a reference to the given []DataIndex and assigns it to the Indexes field.
func (o *DataStoreTableDetail) SetIndexes(v []DataIndex) {
	o.Indexes = v
}

// GetSemanticType returns the SemanticType field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetSemanticType() DataTableSemanticType {
	if o == nil || IsNil(o.SemanticType) {
		var ret DataTableSemanticType
		return ret
	}
	return *o.SemanticType
}

// GetSemanticTypeOk returns a tuple with the SemanticType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetSemanticTypeOk() (*DataTableSemanticType, bool) {
	if o == nil || IsNil(o.SemanticType) {
		return nil, false
	}
	return o.SemanticType, true
}

// HasSemanticType returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasSemanticType() bool {
	if o != nil && !IsNil(o.SemanticType) {
		return true
	}

	return false
}

// SetSemanticType gets a reference to the given DataTableSemanticType and assigns it to the SemanticType field.
func (o *DataStoreTableDetail) SetSemanticType(v DataTableSemanticType) {
	o.SemanticType = &v
}

// GetTags returns the Tags field value
func (o *DataStoreTableDetail) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *DataStoreTableDetail) SetTags(v []string) {
	o.Tags = v
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetRowCount() float32 {
	if o == nil || IsNil(o.RowCount) {
		var ret float32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetRowCountOk() (*float32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given float32 and assigns it to the RowCount field.
func (o *DataStoreTableDetail) SetRowCount(v float32) {
	o.RowCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DataStoreTableDetail) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DataStoreTableDetail) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetSampleData returns the SampleData field value if set, zero value otherwise.
func (o *DataStoreTableDetail) GetSampleData() []map[string]interface{} {
	if o == nil || IsNil(o.SampleData) {
		var ret []map[string]interface{}
		return ret
	}
	return o.SampleData
}

// GetSampleDataOk returns a tuple with the SampleData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreTableDetail) GetSampleDataOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.SampleData) {
		return nil, false
	}
	return o.SampleData, true
}

// HasSampleData returns a boolean if a field has been set.
func (o *DataStoreTableDetail) HasSampleData() bool {
	if o != nil && !IsNil(o.SampleData) {
		return true
	}

	return false
}

// SetSampleData gets a reference to the given []map[string]interface{} and assigns it to the SampleData field.
func (o *DataStoreTableDetail) SetSampleData(v []map[string]interface{}) {
	o.SampleData = v
}

func (o DataStoreTableDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataStoreTableDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["columns"] = o.Columns
	if !IsNil(o.ForeignKeys) {
		toSerialize["foreign_keys"] = o.ForeignKeys
	}
	if !IsNil(o.Indexes) {
		toSerialize["indexes"] = o.Indexes
	}
	if !IsNil(o.SemanticType) {
		toSerialize["semantic_type"] = o.SemanticType
	}
	toSerialize["tags"] = o.Tags
	if !IsNil(o.RowCount) {
		toSerialize["row_count"] = o.RowCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.SampleData) {
		toSerialize["sample_data"] = o.SampleData
	}
	return toSerialize, nil
}

func (o *DataStoreTableDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"columns",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataStoreTableDetail := _DataStoreTableDetail{}

	err = json.Unmarshal(data, &varDataStoreTableDetail)

	if err != nil {
		return err
	}

	*o = DataStoreTableDetail(varDataStoreTableDetail)

	return err
}

type NullableDataStoreTableDetail struct {
	value *DataStoreTableDetail
	isSet bool
}

func (v NullableDataStoreTableDetail) Get() *DataStoreTableDetail {
	return v.value
}

func (v *NullableDataStoreTableDetail) Set(val *DataStoreTableDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableDataStoreTableDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableDataStoreTableDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataStoreTableDetail(val *DataStoreTableDetail) *NullableDataStoreTableDetail {
	return &NullableDataStoreTableDetail{value: val, isSet: true}
}

func (v NullableDataStoreTableDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataStoreTableDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
