/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260807.073259Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AppDevelopmentTaskDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDevelopmentTaskDetails{}

// AppDevelopmentTaskDetails Development task details, including the latest parent assistant run when one exists.
type AppDevelopmentTaskDetails struct {
	// Task slug derived from the branch name.
	Id string `json:"id"`
	// Complete Git branch name.
	Branch string `json:"branch"`
	// Commit currently at the branch head.
	SourceCommit string `json:"source_commit"`
	// Branch-head commit date, when available.
	CommitDate *string `json:"commit_date,omitempty"`
	// Latest Studio Assistant run started for this task branch.
	AgentRun *AgentRunSearchHit `json:"agent_run,omitempty"`
}

type _AppDevelopmentTaskDetails AppDevelopmentTaskDetails

// NewAppDevelopmentTaskDetails instantiates a new AppDevelopmentTaskDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDevelopmentTaskDetails(id string, branch string, sourceCommit string) *AppDevelopmentTaskDetails {
	this := AppDevelopmentTaskDetails{}
	this.Id = id
	this.Branch = branch
	this.SourceCommit = sourceCommit
	return &this
}

// NewAppDevelopmentTaskDetailsWithDefaults instantiates a new AppDevelopmentTaskDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDevelopmentTaskDetailsWithDefaults() *AppDevelopmentTaskDetails {
	this := AppDevelopmentTaskDetails{}
	return &this
}

// GetId returns the Id field value
func (o *AppDevelopmentTaskDetails) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppDevelopmentTaskDetails) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppDevelopmentTaskDetails) SetId(v string) {
	o.Id = v
}

// GetBranch returns the Branch field value
func (o *AppDevelopmentTaskDetails) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *AppDevelopmentTaskDetails) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *AppDevelopmentTaskDetails) SetBranch(v string) {
	o.Branch = v
}

// GetSourceCommit returns the SourceCommit field value
func (o *AppDevelopmentTaskDetails) GetSourceCommit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceCommit
}

// GetSourceCommitOk returns a tuple with the SourceCommit field value
// and a boolean to check if the value has been set.
func (o *AppDevelopmentTaskDetails) GetSourceCommitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceCommit, true
}

// SetSourceCommit sets field value
func (o *AppDevelopmentTaskDetails) SetSourceCommit(v string) {
	o.SourceCommit = v
}

// GetCommitDate returns the CommitDate field value if set, zero value otherwise.
func (o *AppDevelopmentTaskDetails) GetCommitDate() string {
	if o == nil || IsNil(o.CommitDate) {
		var ret string
		return ret
	}
	return *o.CommitDate
}

// GetCommitDateOk returns a tuple with the CommitDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDevelopmentTaskDetails) GetCommitDateOk() (*string, bool) {
	if o == nil || IsNil(o.CommitDate) {
		return nil, false
	}
	return o.CommitDate, true
}

// HasCommitDate returns a boolean if a field has been set.
func (o *AppDevelopmentTaskDetails) HasCommitDate() bool {
	if o != nil && !IsNil(o.CommitDate) {
		return true
	}

	return false
}

// SetCommitDate gets a reference to the given string and assigns it to the CommitDate field.
func (o *AppDevelopmentTaskDetails) SetCommitDate(v string) {
	o.CommitDate = &v
}

// GetAgentRun returns the AgentRun field value if set, zero value otherwise.
func (o *AppDevelopmentTaskDetails) GetAgentRun() AgentRunSearchHit {
	if o == nil || IsNil(o.AgentRun) {
		var ret AgentRunSearchHit
		return ret
	}
	return *o.AgentRun
}

// GetAgentRunOk returns a tuple with the AgentRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDevelopmentTaskDetails) GetAgentRunOk() (*AgentRunSearchHit, bool) {
	if o == nil || IsNil(o.AgentRun) {
		return nil, false
	}
	return o.AgentRun, true
}

// HasAgentRun returns a boolean if a field has been set.
func (o *AppDevelopmentTaskDetails) HasAgentRun() bool {
	if o != nil && !IsNil(o.AgentRun) {
		return true
	}

	return false
}

// SetAgentRun gets a reference to the given AgentRunSearchHit and assigns it to the AgentRun field.
func (o *AppDevelopmentTaskDetails) SetAgentRun(v AgentRunSearchHit) {
	o.AgentRun = &v
}

func (o AppDevelopmentTaskDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDevelopmentTaskDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["branch"] = o.Branch
	toSerialize["source_commit"] = o.SourceCommit
	if !IsNil(o.CommitDate) {
		toSerialize["commit_date"] = o.CommitDate
	}
	if !IsNil(o.AgentRun) {
		toSerialize["agent_run"] = o.AgentRun
	}
	return toSerialize, nil
}

func (o *AppDevelopmentTaskDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"branch",
		"source_commit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppDevelopmentTaskDetails := _AppDevelopmentTaskDetails{}

	err = json.Unmarshal(data, &varAppDevelopmentTaskDetails)

	if err != nil {
		return err
	}

	*o = AppDevelopmentTaskDetails(varAppDevelopmentTaskDetails)

	return err
}

type NullableAppDevelopmentTaskDetails struct {
	value *AppDevelopmentTaskDetails
	isSet bool
}

func (v NullableAppDevelopmentTaskDetails) Get() *AppDevelopmentTaskDetails {
	return v.value
}

func (v *NullableAppDevelopmentTaskDetails) Set(val *AppDevelopmentTaskDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDevelopmentTaskDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDevelopmentTaskDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDevelopmentTaskDetails(val *AppDevelopmentTaskDetails) *NullableAppDevelopmentTaskDetails {
	return &NullableAppDevelopmentTaskDetails{value: val, isSet: true}
}

func (v NullableAppDevelopmentTaskDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDevelopmentTaskDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
