/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModalityDefaults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModalityDefaults{}

// ModalityDefaults Modality-specific default model overrides. These override the base default when specific input modalities are detected.
type ModalityDefaults struct {
	// Override for inputs containing images
	Image *ModelDefault `json:"image,omitempty"`
	// Override for inputs containing video (requires video-capable model)
	Video *ModelDefault `json:"video,omitempty"`
}

// NewModalityDefaults instantiates a new ModalityDefaults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModalityDefaults() *ModalityDefaults {
	this := ModalityDefaults{}
	return &this
}

// NewModalityDefaultsWithDefaults instantiates a new ModalityDefaults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModalityDefaultsWithDefaults() *ModalityDefaults {
	this := ModalityDefaults{}
	return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ModalityDefaults) GetImage() ModelDefault {
	if o == nil || IsNil(o.Image) {
		var ret ModelDefault
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModalityDefaults) GetImageOk() (*ModelDefault, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ModalityDefaults) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given ModelDefault and assigns it to the Image field.
func (o *ModalityDefaults) SetImage(v ModelDefault) {
	o.Image = &v
}

// GetVideo returns the Video field value if set, zero value otherwise.
func (o *ModalityDefaults) GetVideo() ModelDefault {
	if o == nil || IsNil(o.Video) {
		var ret ModelDefault
		return ret
	}
	return *o.Video
}

// GetVideoOk returns a tuple with the Video field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModalityDefaults) GetVideoOk() (*ModelDefault, bool) {
	if o == nil || IsNil(o.Video) {
		return nil, false
	}
	return o.Video, true
}

// HasVideo returns a boolean if a field has been set.
func (o *ModalityDefaults) HasVideo() bool {
	if o != nil && !IsNil(o.Video) {
		return true
	}

	return false
}

// SetVideo gets a reference to the given ModelDefault and assigns it to the Video field.
func (o *ModalityDefaults) SetVideo(v ModelDefault) {
	o.Video = &v
}

func (o ModalityDefaults) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModalityDefaults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Video) {
		toSerialize["video"] = o.Video
	}
	return toSerialize, nil
}

type NullableModalityDefaults struct {
	value *ModalityDefaults
	isSet bool
}

func (v NullableModalityDefaults) Get() *ModalityDefaults {
	return v.value
}

func (v *NullableModalityDefaults) Set(val *ModalityDefaults) {
	v.value = val
	v.isSet = true
}

func (v NullableModalityDefaults) IsSet() bool {
	return v.isSet
}

func (v *NullableModalityDefaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModalityDefaults(val *ModalityDefaults) *NullableModalityDefaults {
	return &NullableModalityDefaults{value: val, isSet: true}
}

func (v NullableModalityDefaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModalityDefaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
