/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TaskTypeSIGNAL the model 'TaskTypeSIGNAL'
type TaskTypeSIGNAL string

// List of TaskType_SIGNAL
const (
	TASKTYPESIGNAL_SIGNAL                   TaskTypeSIGNAL = "signal"
	TASKTYPESIGNAL_UNKNOWN_DEFAULT_OPEN_API TaskTypeSIGNAL = "unknown_default_open_api"
)

// All allowed values of TaskTypeSIGNAL enum
var AllowedTaskTypeSIGNALEnumValues = []TaskTypeSIGNAL{
	"signal",
	"unknown_default_open_api",
}

func (v *TaskTypeSIGNAL) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TaskTypeSIGNAL(value)
	for _, existing := range AllowedTaskTypeSIGNALEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = TASKTYPESIGNAL_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewTaskTypeSIGNALFromValue returns a pointer to a valid TaskTypeSIGNAL
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTaskTypeSIGNALFromValue(v string) (*TaskTypeSIGNAL, error) {
	ev := TaskTypeSIGNAL(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TaskTypeSIGNAL: valid values are %v", v, AllowedTaskTypeSIGNALEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TaskTypeSIGNAL) IsValid() bool {
	for _, existing := range AllowedTaskTypeSIGNALEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TaskType_SIGNAL value
func (v TaskTypeSIGNAL) Ptr() *TaskTypeSIGNAL {
	return &v
}

type NullableTaskTypeSIGNAL struct {
	value *TaskTypeSIGNAL
	isSet bool
}

func (v NullableTaskTypeSIGNAL) Get() *TaskTypeSIGNAL {
	return v.value
}

func (v *NullableTaskTypeSIGNAL) Set(val *TaskTypeSIGNAL) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskTypeSIGNAL) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskTypeSIGNAL) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskTypeSIGNAL(val *TaskTypeSIGNAL) *NullableTaskTypeSIGNAL {
	return &NullableTaskTypeSIGNAL{value: val, isSet: true}
}

func (v NullableTaskTypeSIGNAL) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskTypeSIGNAL) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
