/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.6.0-dev.20260918.061604Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TwelvelabsPegasusOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwelvelabsPegasusOptions{}

// TwelvelabsPegasusOptions struct for TwelvelabsPegasusOptions
type TwelvelabsPegasusOptions struct {
	OptionId    *string  `json:"_option_id,omitempty"`
	Temperature *float32 `json:"temperature,omitempty"`
	MaxTokens   *float32 `json:"max_tokens,omitempty"`
	// Provider-defined processing tier. Unknown non-empty values are preserved for forward compatibility.
	ServiceTier *string `json:"service_tier,omitempty"`
}

// NewTwelvelabsPegasusOptions instantiates a new TwelvelabsPegasusOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwelvelabsPegasusOptions() *TwelvelabsPegasusOptions {
	this := TwelvelabsPegasusOptions{}
	return &this
}

// NewTwelvelabsPegasusOptionsWithDefaults instantiates a new TwelvelabsPegasusOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwelvelabsPegasusOptionsWithDefaults() *TwelvelabsPegasusOptions {
	this := TwelvelabsPegasusOptions{}
	return &this
}

// GetOptionId returns the OptionId field value if set, zero value otherwise.
func (o *TwelvelabsPegasusOptions) GetOptionId() string {
	if o == nil || IsNil(o.OptionId) {
		var ret string
		return ret
	}
	return *o.OptionId
}

// GetOptionIdOk returns a tuple with the OptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwelvelabsPegasusOptions) GetOptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.OptionId) {
		return nil, false
	}
	return o.OptionId, true
}

// HasOptionId returns a boolean if a field has been set.
func (o *TwelvelabsPegasusOptions) HasOptionId() bool {
	if o != nil && !IsNil(o.OptionId) {
		return true
	}

	return false
}

// SetOptionId gets a reference to the given string and assigns it to the OptionId field.
func (o *TwelvelabsPegasusOptions) SetOptionId(v string) {
	o.OptionId = &v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *TwelvelabsPegasusOptions) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature) {
		var ret float32
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwelvelabsPegasusOptions) GetTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *TwelvelabsPegasusOptions) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given float32 and assigns it to the Temperature field.
func (o *TwelvelabsPegasusOptions) SetTemperature(v float32) {
	o.Temperature = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *TwelvelabsPegasusOptions) GetMaxTokens() float32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret float32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwelvelabsPegasusOptions) GetMaxTokensOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *TwelvelabsPegasusOptions) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given float32 and assigns it to the MaxTokens field.
func (o *TwelvelabsPegasusOptions) SetMaxTokens(v float32) {
	o.MaxTokens = &v
}

// GetServiceTier returns the ServiceTier field value if set, zero value otherwise.
func (o *TwelvelabsPegasusOptions) GetServiceTier() string {
	if o == nil || IsNil(o.ServiceTier) {
		var ret string
		return ret
	}
	return *o.ServiceTier
}

// GetServiceTierOk returns a tuple with the ServiceTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwelvelabsPegasusOptions) GetServiceTierOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceTier) {
		return nil, false
	}
	return o.ServiceTier, true
}

// HasServiceTier returns a boolean if a field has been set.
func (o *TwelvelabsPegasusOptions) HasServiceTier() bool {
	if o != nil && !IsNil(o.ServiceTier) {
		return true
	}

	return false
}

// SetServiceTier gets a reference to the given string and assigns it to the ServiceTier field.
func (o *TwelvelabsPegasusOptions) SetServiceTier(v string) {
	o.ServiceTier = &v
}

func (o TwelvelabsPegasusOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwelvelabsPegasusOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OptionId) {
		toSerialize["_option_id"] = o.OptionId
	}
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if !IsNil(o.ServiceTier) {
		toSerialize["service_tier"] = o.ServiceTier
	}
	return toSerialize, nil
}

type NullableTwelvelabsPegasusOptions struct {
	value *TwelvelabsPegasusOptions
	isSet bool
}

func (v NullableTwelvelabsPegasusOptions) Get() *TwelvelabsPegasusOptions {
	return v.value
}

func (v *NullableTwelvelabsPegasusOptions) Set(val *TwelvelabsPegasusOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableTwelvelabsPegasusOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableTwelvelabsPegasusOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwelvelabsPegasusOptions(val *TwelvelabsPegasusOptions) *NullableTwelvelabsPegasusOptions {
	return &NullableTwelvelabsPegasusOptions{value: val, isSet: true}
}

func (v NullableTwelvelabsPegasusOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwelvelabsPegasusOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
