/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260901.005903Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StartProcessTestRunPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartProcessTestRunPayload{}

// StartProcessTestRunPayload struct for StartProcessTestRunPayload
type StartProcessTestRunPayload struct {
	SuiteId           string   `json:"suite_id"`
	ProcessRevisionId string   `json:"process_revision_id"`
	ScenarioIds       []string `json:"scenario_ids,omitempty"`
}

type _StartProcessTestRunPayload StartProcessTestRunPayload

// NewStartProcessTestRunPayload instantiates a new StartProcessTestRunPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartProcessTestRunPayload(suiteId string, processRevisionId string) *StartProcessTestRunPayload {
	this := StartProcessTestRunPayload{}
	this.SuiteId = suiteId
	this.ProcessRevisionId = processRevisionId
	return &this
}

// NewStartProcessTestRunPayloadWithDefaults instantiates a new StartProcessTestRunPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartProcessTestRunPayloadWithDefaults() *StartProcessTestRunPayload {
	this := StartProcessTestRunPayload{}
	return &this
}

// GetSuiteId returns the SuiteId field value
func (o *StartProcessTestRunPayload) GetSuiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuiteId
}

// GetSuiteIdOk returns a tuple with the SuiteId field value
// and a boolean to check if the value has been set.
func (o *StartProcessTestRunPayload) GetSuiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuiteId, true
}

// SetSuiteId sets field value
func (o *StartProcessTestRunPayload) SetSuiteId(v string) {
	o.SuiteId = v
}

// GetProcessRevisionId returns the ProcessRevisionId field value
func (o *StartProcessTestRunPayload) GetProcessRevisionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessRevisionId
}

// GetProcessRevisionIdOk returns a tuple with the ProcessRevisionId field value
// and a boolean to check if the value has been set.
func (o *StartProcessTestRunPayload) GetProcessRevisionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessRevisionId, true
}

// SetProcessRevisionId sets field value
func (o *StartProcessTestRunPayload) SetProcessRevisionId(v string) {
	o.ProcessRevisionId = v
}

// GetScenarioIds returns the ScenarioIds field value if set, zero value otherwise.
func (o *StartProcessTestRunPayload) GetScenarioIds() []string {
	if o == nil || IsNil(o.ScenarioIds) {
		var ret []string
		return ret
	}
	return o.ScenarioIds
}

// GetScenarioIdsOk returns a tuple with the ScenarioIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartProcessTestRunPayload) GetScenarioIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ScenarioIds) {
		return nil, false
	}
	return o.ScenarioIds, true
}

// HasScenarioIds returns a boolean if a field has been set.
func (o *StartProcessTestRunPayload) HasScenarioIds() bool {
	if o != nil && !IsNil(o.ScenarioIds) {
		return true
	}

	return false
}

// SetScenarioIds gets a reference to the given []string and assigns it to the ScenarioIds field.
func (o *StartProcessTestRunPayload) SetScenarioIds(v []string) {
	o.ScenarioIds = v
}

func (o StartProcessTestRunPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartProcessTestRunPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["suite_id"] = o.SuiteId
	toSerialize["process_revision_id"] = o.ProcessRevisionId
	if !IsNil(o.ScenarioIds) {
		toSerialize["scenario_ids"] = o.ScenarioIds
	}
	return toSerialize, nil
}

func (o *StartProcessTestRunPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"suite_id",
		"process_revision_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStartProcessTestRunPayload := _StartProcessTestRunPayload{}

	err = json.Unmarshal(data, &varStartProcessTestRunPayload)

	if err != nil {
		return err
	}

	*o = StartProcessTestRunPayload(varStartProcessTestRunPayload)

	return err
}

type NullableStartProcessTestRunPayload struct {
	value *StartProcessTestRunPayload
	isSet bool
}

func (v NullableStartProcessTestRunPayload) Get() *StartProcessTestRunPayload {
	return v.value
}

func (v *NullableStartProcessTestRunPayload) Set(val *StartProcessTestRunPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableStartProcessTestRunPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableStartProcessTestRunPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartProcessTestRunPayload(val *StartProcessTestRunPayload) *NullableStartProcessTestRunPayload {
	return &NullableStartProcessTestRunPayload{value: val, isSet: true}
}

func (v NullableStartProcessTestRunPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartProcessTestRunPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
