/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReindexAgentRunsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReindexAgentRunsResponse{}

// ReindexAgentRunsResponse struct for ReindexAgentRunsResponse
type ReindexAgentRunsResponse struct {
	Status               string                                `json:"status"`
	Backend              ElasticsearchBackend                  `json:"backend"`
	IndexName            string                                `json:"index_name"`
	Recreated            bool                                  `json:"recreated"`
	Total                float32                               `json:"total"`
	Scanned              float32                               `json:"scanned"`
	Indexed              float32                               `json:"indexed"`
	Failed               float32                               `json:"failed"`
	Errors               []ReindexAgentRunsResponseErrorsInner `json:"errors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReindexAgentRunsResponse ReindexAgentRunsResponse

// NewReindexAgentRunsResponse instantiates a new ReindexAgentRunsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReindexAgentRunsResponse(status string, backend ElasticsearchBackend, indexName string, recreated bool, total float32, scanned float32, indexed float32, failed float32) *ReindexAgentRunsResponse {
	this := ReindexAgentRunsResponse{}
	this.Status = status
	this.Backend = backend
	this.IndexName = indexName
	this.Recreated = recreated
	this.Total = total
	this.Scanned = scanned
	this.Indexed = indexed
	this.Failed = failed
	return &this
}

// NewReindexAgentRunsResponseWithDefaults instantiates a new ReindexAgentRunsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReindexAgentRunsResponseWithDefaults() *ReindexAgentRunsResponse {
	this := ReindexAgentRunsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *ReindexAgentRunsResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReindexAgentRunsResponse) SetStatus(v string) {
	o.Status = v
}

// GetBackend returns the Backend field value
func (o *ReindexAgentRunsResponse) GetBackend() ElasticsearchBackend {
	if o == nil {
		var ret ElasticsearchBackend
		return ret
	}

	return o.Backend
}

// GetBackendOk returns a tuple with the Backend field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetBackendOk() (*ElasticsearchBackend, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backend, true
}

// SetBackend sets field value
func (o *ReindexAgentRunsResponse) SetBackend(v ElasticsearchBackend) {
	o.Backend = v
}

// GetIndexName returns the IndexName field value
func (o *ReindexAgentRunsResponse) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetIndexNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *ReindexAgentRunsResponse) SetIndexName(v string) {
	o.IndexName = v
}

// GetRecreated returns the Recreated field value
func (o *ReindexAgentRunsResponse) GetRecreated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Recreated
}

// GetRecreatedOk returns a tuple with the Recreated field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetRecreatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recreated, true
}

// SetRecreated sets field value
func (o *ReindexAgentRunsResponse) SetRecreated(v bool) {
	o.Recreated = v
}

// GetTotal returns the Total field value
func (o *ReindexAgentRunsResponse) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ReindexAgentRunsResponse) SetTotal(v float32) {
	o.Total = v
}

// GetScanned returns the Scanned field value
func (o *ReindexAgentRunsResponse) GetScanned() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Scanned
}

// GetScannedOk returns a tuple with the Scanned field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetScannedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scanned, true
}

// SetScanned sets field value
func (o *ReindexAgentRunsResponse) SetScanned(v float32) {
	o.Scanned = v
}

// GetIndexed returns the Indexed field value
func (o *ReindexAgentRunsResponse) GetIndexed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Indexed
}

// GetIndexedOk returns a tuple with the Indexed field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetIndexedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Indexed, true
}

// SetIndexed sets field value
func (o *ReindexAgentRunsResponse) SetIndexed(v float32) {
	o.Indexed = v
}

// GetFailed returns the Failed field value
func (o *ReindexAgentRunsResponse) GetFailed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetFailedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *ReindexAgentRunsResponse) SetFailed(v float32) {
	o.Failed = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ReindexAgentRunsResponse) GetErrors() []ReindexAgentRunsResponseErrorsInner {
	if o == nil || IsNil(o.Errors) {
		var ret []ReindexAgentRunsResponseErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReindexAgentRunsResponse) GetErrorsOk() ([]ReindexAgentRunsResponseErrorsInner, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ReindexAgentRunsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ReindexAgentRunsResponseErrorsInner and assigns it to the Errors field.
func (o *ReindexAgentRunsResponse) SetErrors(v []ReindexAgentRunsResponseErrorsInner) {
	o.Errors = v
}

func (o ReindexAgentRunsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReindexAgentRunsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["backend"] = o.Backend
	toSerialize["index_name"] = o.IndexName
	toSerialize["recreated"] = o.Recreated
	toSerialize["total"] = o.Total
	toSerialize["scanned"] = o.Scanned
	toSerialize["indexed"] = o.Indexed
	toSerialize["failed"] = o.Failed
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReindexAgentRunsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"backend",
		"index_name",
		"recreated",
		"total",
		"scanned",
		"indexed",
		"failed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReindexAgentRunsResponse := _ReindexAgentRunsResponse{}

	err = json.Unmarshal(data, &varReindexAgentRunsResponse)

	if err != nil {
		return err
	}

	*o = ReindexAgentRunsResponse(varReindexAgentRunsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "backend")
		delete(additionalProperties, "index_name")
		delete(additionalProperties, "recreated")
		delete(additionalProperties, "total")
		delete(additionalProperties, "scanned")
		delete(additionalProperties, "indexed")
		delete(additionalProperties, "failed")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReindexAgentRunsResponse struct {
	value *ReindexAgentRunsResponse
	isSet bool
}

func (v NullableReindexAgentRunsResponse) Get() *ReindexAgentRunsResponse {
	return v.value
}

func (v *NullableReindexAgentRunsResponse) Set(val *ReindexAgentRunsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReindexAgentRunsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReindexAgentRunsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReindexAgentRunsResponse(val *ReindexAgentRunsResponse) *NullableReindexAgentRunsResponse {
	return &NullableReindexAgentRunsResponse{value: val, isSet: true}
}

func (v NullableReindexAgentRunsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReindexAgentRunsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
