/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PartialAgentMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartialAgentMessage{}

// PartialAgentMessage struct for PartialAgentMessage
type PartialAgentMessage struct {
	Timestamp     *float32             `json:"timestamp,omitempty"`
	WorkflowRunId *string              `json:"workflow_run_id,omitempty"`
	Type          *AgentMessageType    `json:"type,omitempty"`
	Message       *string              `json:"message,omitempty"`
	Details       *AgentMessageDetails `json:"details,omitempty"`
	WorkstreamId  *string              `json:"workstream_id,omitempty"`
}

// NewPartialAgentMessage instantiates a new PartialAgentMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartialAgentMessage() *PartialAgentMessage {
	this := PartialAgentMessage{}
	return &this
}

// NewPartialAgentMessageWithDefaults instantiates a new PartialAgentMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartialAgentMessageWithDefaults() *PartialAgentMessage {
	this := PartialAgentMessage{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *PartialAgentMessage) GetTimestamp() float32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret float32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialAgentMessage) GetTimestampOk() (*float32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *PartialAgentMessage) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given float32 and assigns it to the Timestamp field.
func (o *PartialAgentMessage) SetTimestamp(v float32) {
	o.Timestamp = &v
}

// GetWorkflowRunId returns the WorkflowRunId field value if set, zero value otherwise.
func (o *PartialAgentMessage) GetWorkflowRunId() string {
	if o == nil || IsNil(o.WorkflowRunId) {
		var ret string
		return ret
	}
	return *o.WorkflowRunId
}

// GetWorkflowRunIdOk returns a tuple with the WorkflowRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialAgentMessage) GetWorkflowRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowRunId) {
		return nil, false
	}
	return o.WorkflowRunId, true
}

// HasWorkflowRunId returns a boolean if a field has been set.
func (o *PartialAgentMessage) HasWorkflowRunId() bool {
	if o != nil && !IsNil(o.WorkflowRunId) {
		return true
	}

	return false
}

// SetWorkflowRunId gets a reference to the given string and assigns it to the WorkflowRunId field.
func (o *PartialAgentMessage) SetWorkflowRunId(v string) {
	o.WorkflowRunId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PartialAgentMessage) GetType() AgentMessageType {
	if o == nil || IsNil(o.Type) {
		var ret AgentMessageType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialAgentMessage) GetTypeOk() (*AgentMessageType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PartialAgentMessage) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given AgentMessageType and assigns it to the Type field.
func (o *PartialAgentMessage) SetType(v AgentMessageType) {
	o.Type = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PartialAgentMessage) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialAgentMessage) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PartialAgentMessage) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PartialAgentMessage) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *PartialAgentMessage) GetDetails() AgentMessageDetails {
	if o == nil || IsNil(o.Details) {
		var ret AgentMessageDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialAgentMessage) GetDetailsOk() (*AgentMessageDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *PartialAgentMessage) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given AgentMessageDetails and assigns it to the Details field.
func (o *PartialAgentMessage) SetDetails(v AgentMessageDetails) {
	o.Details = &v
}

// GetWorkstreamId returns the WorkstreamId field value if set, zero value otherwise.
func (o *PartialAgentMessage) GetWorkstreamId() string {
	if o == nil || IsNil(o.WorkstreamId) {
		var ret string
		return ret
	}
	return *o.WorkstreamId
}

// GetWorkstreamIdOk returns a tuple with the WorkstreamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialAgentMessage) GetWorkstreamIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkstreamId) {
		return nil, false
	}
	return o.WorkstreamId, true
}

// HasWorkstreamId returns a boolean if a field has been set.
func (o *PartialAgentMessage) HasWorkstreamId() bool {
	if o != nil && !IsNil(o.WorkstreamId) {
		return true
	}

	return false
}

// SetWorkstreamId gets a reference to the given string and assigns it to the WorkstreamId field.
func (o *PartialAgentMessage) SetWorkstreamId(v string) {
	o.WorkstreamId = &v
}

func (o PartialAgentMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartialAgentMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.WorkflowRunId) {
		toSerialize["workflow_run_id"] = o.WorkflowRunId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.WorkstreamId) {
		toSerialize["workstream_id"] = o.WorkstreamId
	}
	return toSerialize, nil
}

type NullablePartialAgentMessage struct {
	value *PartialAgentMessage
	isSet bool
}

func (v NullablePartialAgentMessage) Get() *PartialAgentMessage {
	return v.value
}

func (v *NullablePartialAgentMessage) Set(val *PartialAgentMessage) {
	v.value = val
	v.isSet = true
}

func (v NullablePartialAgentMessage) IsSet() bool {
	return v.isSet
}

func (v *NullablePartialAgentMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartialAgentMessage(val *PartialAgentMessage) *NullablePartialAgentMessage {
	return &NullablePartialAgentMessage{value: val, isSet: true}
}

func (v NullablePartialAgentMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartialAgentMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
