/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EventSubscriptionFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSubscriptionFilter{}

// EventSubscriptionFilter struct for EventSubscriptionFilter
type EventSubscriptionFilter struct {
	EventCategory        []string               `json:"event_category,omitempty"`
	ExcludeEventCategory []EventCategory        `json:"exclude_event_category,omitempty"`
	Action               []string               `json:"action,omitempty"`
	ResourceType         []string               `json:"resource_type,omitempty"`
	Condition            map[string]interface{} `json:"condition,omitempty"`
	// LLM-evaluated predicate applied after all structural filters have matched.
	SemanticCondition *EventSemanticCondition `json:"semantic_condition,omitempty"`
}

// NewEventSubscriptionFilter instantiates a new EventSubscriptionFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSubscriptionFilter() *EventSubscriptionFilter {
	this := EventSubscriptionFilter{}
	return &this
}

// NewEventSubscriptionFilterWithDefaults instantiates a new EventSubscriptionFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSubscriptionFilterWithDefaults() *EventSubscriptionFilter {
	this := EventSubscriptionFilter{}
	return &this
}

// GetEventCategory returns the EventCategory field value if set, zero value otherwise.
func (o *EventSubscriptionFilter) GetEventCategory() []string {
	if o == nil || IsNil(o.EventCategory) {
		var ret []string
		return ret
	}
	return o.EventCategory
}

// GetEventCategoryOk returns a tuple with the EventCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSubscriptionFilter) GetEventCategoryOk() ([]string, bool) {
	if o == nil || IsNil(o.EventCategory) {
		return nil, false
	}
	return o.EventCategory, true
}

// HasEventCategory returns a boolean if a field has been set.
func (o *EventSubscriptionFilter) HasEventCategory() bool {
	if o != nil && !IsNil(o.EventCategory) {
		return true
	}

	return false
}

// SetEventCategory gets a reference to the given []string and assigns it to the EventCategory field.
func (o *EventSubscriptionFilter) SetEventCategory(v []string) {
	o.EventCategory = v
}

// GetExcludeEventCategory returns the ExcludeEventCategory field value if set, zero value otherwise.
func (o *EventSubscriptionFilter) GetExcludeEventCategory() []EventCategory {
	if o == nil || IsNil(o.ExcludeEventCategory) {
		var ret []EventCategory
		return ret
	}
	return o.ExcludeEventCategory
}

// GetExcludeEventCategoryOk returns a tuple with the ExcludeEventCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSubscriptionFilter) GetExcludeEventCategoryOk() ([]EventCategory, bool) {
	if o == nil || IsNil(o.ExcludeEventCategory) {
		return nil, false
	}
	return o.ExcludeEventCategory, true
}

// HasExcludeEventCategory returns a boolean if a field has been set.
func (o *EventSubscriptionFilter) HasExcludeEventCategory() bool {
	if o != nil && !IsNil(o.ExcludeEventCategory) {
		return true
	}

	return false
}

// SetExcludeEventCategory gets a reference to the given []EventCategory and assigns it to the ExcludeEventCategory field.
func (o *EventSubscriptionFilter) SetExcludeEventCategory(v []EventCategory) {
	o.ExcludeEventCategory = v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *EventSubscriptionFilter) GetAction() []string {
	if o == nil || IsNil(o.Action) {
		var ret []string
		return ret
	}
	return o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSubscriptionFilter) GetActionOk() ([]string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *EventSubscriptionFilter) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given []string and assigns it to the Action field.
func (o *EventSubscriptionFilter) SetAction(v []string) {
	o.Action = v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *EventSubscriptionFilter) GetResourceType() []string {
	if o == nil || IsNil(o.ResourceType) {
		var ret []string
		return ret
	}
	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSubscriptionFilter) GetResourceTypeOk() ([]string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *EventSubscriptionFilter) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given []string and assigns it to the ResourceType field.
func (o *EventSubscriptionFilter) SetResourceType(v []string) {
	o.ResourceType = v
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *EventSubscriptionFilter) GetCondition() map[string]interface{} {
	if o == nil || IsNil(o.Condition) {
		var ret map[string]interface{}
		return ret
	}
	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSubscriptionFilter) GetConditionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Condition) {
		return map[string]interface{}{}, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *EventSubscriptionFilter) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given map[string]interface{} and assigns it to the Condition field.
func (o *EventSubscriptionFilter) SetCondition(v map[string]interface{}) {
	o.Condition = v
}

// GetSemanticCondition returns the SemanticCondition field value if set, zero value otherwise.
func (o *EventSubscriptionFilter) GetSemanticCondition() EventSemanticCondition {
	if o == nil || IsNil(o.SemanticCondition) {
		var ret EventSemanticCondition
		return ret
	}
	return *o.SemanticCondition
}

// GetSemanticConditionOk returns a tuple with the SemanticCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSubscriptionFilter) GetSemanticConditionOk() (*EventSemanticCondition, bool) {
	if o == nil || IsNil(o.SemanticCondition) {
		return nil, false
	}
	return o.SemanticCondition, true
}

// HasSemanticCondition returns a boolean if a field has been set.
func (o *EventSubscriptionFilter) HasSemanticCondition() bool {
	if o != nil && !IsNil(o.SemanticCondition) {
		return true
	}

	return false
}

// SetSemanticCondition gets a reference to the given EventSemanticCondition and assigns it to the SemanticCondition field.
func (o *EventSubscriptionFilter) SetSemanticCondition(v EventSemanticCondition) {
	o.SemanticCondition = &v
}

func (o EventSubscriptionFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSubscriptionFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventCategory) {
		toSerialize["event_category"] = o.EventCategory
	}
	if !IsNil(o.ExcludeEventCategory) {
		toSerialize["exclude_event_category"] = o.ExcludeEventCategory
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resource_type"] = o.ResourceType
	}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if !IsNil(o.SemanticCondition) {
		toSerialize["semantic_condition"] = o.SemanticCondition
	}
	return toSerialize, nil
}

type NullableEventSubscriptionFilter struct {
	value *EventSubscriptionFilter
	isSet bool
}

func (v NullableEventSubscriptionFilter) Get() *EventSubscriptionFilter {
	return v.value
}

func (v *NullableEventSubscriptionFilter) Set(val *EventSubscriptionFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSubscriptionFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSubscriptionFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSubscriptionFilter(val *EventSubscriptionFilter) *NullableEventSubscriptionFilter {
	return &NullableEventSubscriptionFilter{value: val, isSet: true}
}

func (v NullableEventSubscriptionFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSubscriptionFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
