/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the InteractionUpdatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InteractionUpdatePayload{}

// InteractionUpdatePayload struct for InteractionUpdatePayload
type InteractionUpdatePayload struct {
	Status             *InteractionStatus       `json:"status,omitempty"`
	Parent             *string                  `json:"parent,omitempty"`
	Visibility         *InteractionVisibility   `json:"visibility,omitempty"`
	Version            *float32                 `json:"version,omitempty"`
	TestData           map[string]interface{}   `json:"test_data,omitempty"`
	InteractionSchema  *InteractionResultSchema `json:"interaction_schema,omitempty"`
	CachePolicy        *CachePolicy             `json:"cache_policy,omitempty"`
	Prompts            []PromptSegmentDef       `json:"prompts,omitempty"`
	LastPublishedAt    *time.Time               `json:"last_published_at,omitempty"`
	Name               *string                  `json:"name,omitempty"`
	Endpoint           *string                  `json:"endpoint,omitempty"`
	Description        *string                  `json:"description,omitempty"`
	Tags               []string                 `json:"tags,omitempty"`
	AgentRunnerOptions *AgentRunnerOptions      `json:"agent_runner_options,omitempty"`
	Environment        *InteractionEnvironment  `json:"environment,omitempty"`
	Model              *string                  `json:"model,omitempty"`
	ModelOptions       *ModelOptions            `json:"model_options,omitempty"`
	Restriction        *RunDataStorageLevel     `json:"restriction,omitempty"`
	// Deprecated: This is deprecated. Use CompletionResult.type information instead.
	// Deprecated
	OutputModality *Modalities                                  `json:"output_modality,omitempty"`
	ResultSchema   NullableInteractionUpdatePayloadResultSchema `json:"result_schema,omitempty"`
}

// NewInteractionUpdatePayload instantiates a new InteractionUpdatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInteractionUpdatePayload() *InteractionUpdatePayload {
	this := InteractionUpdatePayload{}
	return &this
}

// NewInteractionUpdatePayloadWithDefaults instantiates a new InteractionUpdatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInteractionUpdatePayloadWithDefaults() *InteractionUpdatePayload {
	this := InteractionUpdatePayload{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetStatus() InteractionStatus {
	if o == nil || IsNil(o.Status) {
		var ret InteractionStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetStatusOk() (*InteractionStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InteractionStatus and assigns it to the Status field.
func (o *InteractionUpdatePayload) SetStatus(v InteractionStatus) {
	o.Status = &v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *InteractionUpdatePayload) SetParent(v string) {
	o.Parent = &v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetVisibility() InteractionVisibility {
	if o == nil || IsNil(o.Visibility) {
		var ret InteractionVisibility
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetVisibilityOk() (*InteractionVisibility, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given InteractionVisibility and assigns it to the Visibility field.
func (o *InteractionUpdatePayload) SetVisibility(v InteractionVisibility) {
	o.Visibility = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetVersion() float32 {
	if o == nil || IsNil(o.Version) {
		var ret float32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetVersionOk() (*float32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given float32 and assigns it to the Version field.
func (o *InteractionUpdatePayload) SetVersion(v float32) {
	o.Version = &v
}

// GetTestData returns the TestData field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetTestData() map[string]interface{} {
	if o == nil || IsNil(o.TestData) {
		var ret map[string]interface{}
		return ret
	}
	return o.TestData
}

// GetTestDataOk returns a tuple with the TestData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetTestDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TestData) {
		return map[string]interface{}{}, false
	}
	return o.TestData, true
}

// HasTestData returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasTestData() bool {
	if o != nil && !IsNil(o.TestData) {
		return true
	}

	return false
}

// SetTestData gets a reference to the given map[string]interface{} and assigns it to the TestData field.
func (o *InteractionUpdatePayload) SetTestData(v map[string]interface{}) {
	o.TestData = v
}

// GetInteractionSchema returns the InteractionSchema field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetInteractionSchema() InteractionResultSchema {
	if o == nil || IsNil(o.InteractionSchema) {
		var ret InteractionResultSchema
		return ret
	}
	return *o.InteractionSchema
}

// GetInteractionSchemaOk returns a tuple with the InteractionSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetInteractionSchemaOk() (*InteractionResultSchema, bool) {
	if o == nil || IsNil(o.InteractionSchema) {
		return nil, false
	}
	return o.InteractionSchema, true
}

// HasInteractionSchema returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasInteractionSchema() bool {
	if o != nil && !IsNil(o.InteractionSchema) {
		return true
	}

	return false
}

// SetInteractionSchema gets a reference to the given InteractionResultSchema and assigns it to the InteractionSchema field.
func (o *InteractionUpdatePayload) SetInteractionSchema(v InteractionResultSchema) {
	o.InteractionSchema = &v
}

// GetCachePolicy returns the CachePolicy field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetCachePolicy() CachePolicy {
	if o == nil || IsNil(o.CachePolicy) {
		var ret CachePolicy
		return ret
	}
	return *o.CachePolicy
}

// GetCachePolicyOk returns a tuple with the CachePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetCachePolicyOk() (*CachePolicy, bool) {
	if o == nil || IsNil(o.CachePolicy) {
		return nil, false
	}
	return o.CachePolicy, true
}

// HasCachePolicy returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasCachePolicy() bool {
	if o != nil && !IsNil(o.CachePolicy) {
		return true
	}

	return false
}

// SetCachePolicy gets a reference to the given CachePolicy and assigns it to the CachePolicy field.
func (o *InteractionUpdatePayload) SetCachePolicy(v CachePolicy) {
	o.CachePolicy = &v
}

// GetPrompts returns the Prompts field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetPrompts() []PromptSegmentDef {
	if o == nil || IsNil(o.Prompts) {
		var ret []PromptSegmentDef
		return ret
	}
	return o.Prompts
}

// GetPromptsOk returns a tuple with the Prompts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetPromptsOk() ([]PromptSegmentDef, bool) {
	if o == nil || IsNil(o.Prompts) {
		return nil, false
	}
	return o.Prompts, true
}

// HasPrompts returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasPrompts() bool {
	if o != nil && !IsNil(o.Prompts) {
		return true
	}

	return false
}

// SetPrompts gets a reference to the given []PromptSegmentDef and assigns it to the Prompts field.
func (o *InteractionUpdatePayload) SetPrompts(v []PromptSegmentDef) {
	o.Prompts = v
}

// GetLastPublishedAt returns the LastPublishedAt field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetLastPublishedAt() time.Time {
	if o == nil || IsNil(o.LastPublishedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastPublishedAt
}

// GetLastPublishedAtOk returns a tuple with the LastPublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetLastPublishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastPublishedAt) {
		return nil, false
	}
	return o.LastPublishedAt, true
}

// HasLastPublishedAt returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasLastPublishedAt() bool {
	if o != nil && !IsNil(o.LastPublishedAt) {
		return true
	}

	return false
}

// SetLastPublishedAt gets a reference to the given time.Time and assigns it to the LastPublishedAt field.
func (o *InteractionUpdatePayload) SetLastPublishedAt(v time.Time) {
	o.LastPublishedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InteractionUpdatePayload) SetName(v string) {
	o.Name = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *InteractionUpdatePayload) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InteractionUpdatePayload) SetDescription(v string) {
	o.Description = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *InteractionUpdatePayload) SetTags(v []string) {
	o.Tags = v
}

// GetAgentRunnerOptions returns the AgentRunnerOptions field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetAgentRunnerOptions() AgentRunnerOptions {
	if o == nil || IsNil(o.AgentRunnerOptions) {
		var ret AgentRunnerOptions
		return ret
	}
	return *o.AgentRunnerOptions
}

// GetAgentRunnerOptionsOk returns a tuple with the AgentRunnerOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetAgentRunnerOptionsOk() (*AgentRunnerOptions, bool) {
	if o == nil || IsNil(o.AgentRunnerOptions) {
		return nil, false
	}
	return o.AgentRunnerOptions, true
}

// HasAgentRunnerOptions returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasAgentRunnerOptions() bool {
	if o != nil && !IsNil(o.AgentRunnerOptions) {
		return true
	}

	return false
}

// SetAgentRunnerOptions gets a reference to the given AgentRunnerOptions and assigns it to the AgentRunnerOptions field.
func (o *InteractionUpdatePayload) SetAgentRunnerOptions(v AgentRunnerOptions) {
	o.AgentRunnerOptions = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetEnvironment() InteractionEnvironment {
	if o == nil || IsNil(o.Environment) {
		var ret InteractionEnvironment
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetEnvironmentOk() (*InteractionEnvironment, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given InteractionEnvironment and assigns it to the Environment field.
func (o *InteractionUpdatePayload) SetEnvironment(v InteractionEnvironment) {
	o.Environment = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *InteractionUpdatePayload) SetModel(v string) {
	o.Model = &v
}

// GetModelOptions returns the ModelOptions field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetModelOptions() ModelOptions {
	if o == nil || IsNil(o.ModelOptions) {
		var ret ModelOptions
		return ret
	}
	return *o.ModelOptions
}

// GetModelOptionsOk returns a tuple with the ModelOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetModelOptionsOk() (*ModelOptions, bool) {
	if o == nil || IsNil(o.ModelOptions) {
		return nil, false
	}
	return o.ModelOptions, true
}

// HasModelOptions returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasModelOptions() bool {
	if o != nil && !IsNil(o.ModelOptions) {
		return true
	}

	return false
}

// SetModelOptions gets a reference to the given ModelOptions and assigns it to the ModelOptions field.
func (o *InteractionUpdatePayload) SetModelOptions(v ModelOptions) {
	o.ModelOptions = &v
}

// GetRestriction returns the Restriction field value if set, zero value otherwise.
func (o *InteractionUpdatePayload) GetRestriction() RunDataStorageLevel {
	if o == nil || IsNil(o.Restriction) {
		var ret RunDataStorageLevel
		return ret
	}
	return *o.Restriction
}

// GetRestrictionOk returns a tuple with the Restriction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionUpdatePayload) GetRestrictionOk() (*RunDataStorageLevel, bool) {
	if o == nil || IsNil(o.Restriction) {
		return nil, false
	}
	return o.Restriction, true
}

// HasRestriction returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasRestriction() bool {
	if o != nil && !IsNil(o.Restriction) {
		return true
	}

	return false
}

// SetRestriction gets a reference to the given RunDataStorageLevel and assigns it to the Restriction field.
func (o *InteractionUpdatePayload) SetRestriction(v RunDataStorageLevel) {
	o.Restriction = &v
}

// GetOutputModality returns the OutputModality field value if set, zero value otherwise.
// Deprecated
func (o *InteractionUpdatePayload) GetOutputModality() Modalities {
	if o == nil || IsNil(o.OutputModality) {
		var ret Modalities
		return ret
	}
	return *o.OutputModality
}

// GetOutputModalityOk returns a tuple with the OutputModality field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *InteractionUpdatePayload) GetOutputModalityOk() (*Modalities, bool) {
	if o == nil || IsNil(o.OutputModality) {
		return nil, false
	}
	return o.OutputModality, true
}

// HasOutputModality returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasOutputModality() bool {
	if o != nil && !IsNil(o.OutputModality) {
		return true
	}

	return false
}

// SetOutputModality gets a reference to the given Modalities and assigns it to the OutputModality field.
// Deprecated
func (o *InteractionUpdatePayload) SetOutputModality(v Modalities) {
	o.OutputModality = &v
}

// GetResultSchema returns the ResultSchema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InteractionUpdatePayload) GetResultSchema() InteractionUpdatePayloadResultSchema {
	if o == nil || IsNil(o.ResultSchema.Get()) {
		var ret InteractionUpdatePayloadResultSchema
		return ret
	}
	return *o.ResultSchema.Get()
}

// GetResultSchemaOk returns a tuple with the ResultSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InteractionUpdatePayload) GetResultSchemaOk() (*InteractionUpdatePayloadResultSchema, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultSchema.Get(), o.ResultSchema.IsSet()
}

// HasResultSchema returns a boolean if a field has been set.
func (o *InteractionUpdatePayload) HasResultSchema() bool {
	if o != nil && o.ResultSchema.IsSet() {
		return true
	}

	return false
}

// SetResultSchema gets a reference to the given NullableInteractionUpdatePayloadResultSchema and assigns it to the ResultSchema field.
func (o *InteractionUpdatePayload) SetResultSchema(v InteractionUpdatePayloadResultSchema) {
	o.ResultSchema.Set(&v)
}

// SetResultSchemaNil sets the value for ResultSchema to be an explicit nil
func (o *InteractionUpdatePayload) SetResultSchemaNil() {
	o.ResultSchema.Set(nil)
}

// UnsetResultSchema ensures that no value is present for ResultSchema, not even an explicit nil
func (o *InteractionUpdatePayload) UnsetResultSchema() {
	o.ResultSchema.Unset()
}

func (o InteractionUpdatePayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InteractionUpdatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.TestData) {
		toSerialize["test_data"] = o.TestData
	}
	if !IsNil(o.InteractionSchema) {
		toSerialize["interaction_schema"] = o.InteractionSchema
	}
	if !IsNil(o.CachePolicy) {
		toSerialize["cache_policy"] = o.CachePolicy
	}
	if !IsNil(o.Prompts) {
		toSerialize["prompts"] = o.Prompts
	}
	if !IsNil(o.LastPublishedAt) {
		toSerialize["last_published_at"] = o.LastPublishedAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.AgentRunnerOptions) {
		toSerialize["agent_runner_options"] = o.AgentRunnerOptions
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ModelOptions) {
		toSerialize["model_options"] = o.ModelOptions
	}
	if !IsNil(o.Restriction) {
		toSerialize["restriction"] = o.Restriction
	}
	if !IsNil(o.OutputModality) {
		toSerialize["output_modality"] = o.OutputModality
	}
	if o.ResultSchema.IsSet() {
		toSerialize["result_schema"] = o.ResultSchema.Get()
	}
	return toSerialize, nil
}

type NullableInteractionUpdatePayload struct {
	value *InteractionUpdatePayload
	isSet bool
}

func (v NullableInteractionUpdatePayload) Get() *InteractionUpdatePayload {
	return v.value
}

func (v *NullableInteractionUpdatePayload) Set(val *InteractionUpdatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableInteractionUpdatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableInteractionUpdatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInteractionUpdatePayload(val *InteractionUpdatePayload) *NullableInteractionUpdatePayload {
	return &NullableInteractionUpdatePayload{value: val, isSet: true}
}

func (v NullableInteractionUpdatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInteractionUpdatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
