/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SemanticConditionMode the model 'SemanticConditionMode'
type SemanticConditionMode string

// List of SemanticConditionMode
const (
	SEMANTICCONDITIONMODE_ENFORCE                  SemanticConditionMode = "enforce"
	SEMANTICCONDITIONMODE_SHADOW                   SemanticConditionMode = "shadow"
	SEMANTICCONDITIONMODE_UNKNOWN_DEFAULT_OPEN_API SemanticConditionMode = "unknown_default_open_api"
)

// All allowed values of SemanticConditionMode enum
var AllowedSemanticConditionModeEnumValues = []SemanticConditionMode{
	"enforce",
	"shadow",
	"unknown_default_open_api",
}

func (v *SemanticConditionMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SemanticConditionMode(value)
	for _, existing := range AllowedSemanticConditionModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SEMANTICCONDITIONMODE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewSemanticConditionModeFromValue returns a pointer to a valid SemanticConditionMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSemanticConditionModeFromValue(v string) (*SemanticConditionMode, error) {
	ev := SemanticConditionMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SemanticConditionMode: valid values are %v", v, AllowedSemanticConditionModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SemanticConditionMode) IsValid() bool {
	for _, existing := range AllowedSemanticConditionModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SemanticConditionMode value
func (v SemanticConditionMode) Ptr() *SemanticConditionMode {
	return &v
}

type NullableSemanticConditionMode struct {
	value *SemanticConditionMode
	isSet bool
}

func (v NullableSemanticConditionMode) Get() *SemanticConditionMode {
	return v.value
}

func (v *NullableSemanticConditionMode) Set(val *SemanticConditionMode) {
	v.value = val
	v.isSet = true
}

func (v NullableSemanticConditionMode) IsSet() bool {
	return v.isSet
}

func (v *NullableSemanticConditionMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSemanticConditionMode(val *SemanticConditionMode) *NullableSemanticConditionMode {
	return &NullableSemanticConditionMode{value: val, isSet: true}
}

func (v NullableSemanticConditionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSemanticConditionMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
