/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PublishProcessDefinitionPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishProcessDefinitionPayload{}

// PublishProcessDefinitionPayload struct for PublishProcessDefinitionPayload
type PublishProcessDefinitionPayload struct {
	// Required explicit confirmation from the caller.
	Confirmed bool `json:"confirmed"`
	// Optional tags to merge into the published revision.
	Tags []string `json:"tags,omitempty"`
	// Optional human-readable revision label.
	Label *string `json:"label,omitempty"`
	// Optional publish note.
	Comment *string `json:"comment,omitempty"`
}

type _PublishProcessDefinitionPayload PublishProcessDefinitionPayload

// NewPublishProcessDefinitionPayload instantiates a new PublishProcessDefinitionPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishProcessDefinitionPayload(confirmed bool) *PublishProcessDefinitionPayload {
	this := PublishProcessDefinitionPayload{}
	this.Confirmed = confirmed
	return &this
}

// NewPublishProcessDefinitionPayloadWithDefaults instantiates a new PublishProcessDefinitionPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishProcessDefinitionPayloadWithDefaults() *PublishProcessDefinitionPayload {
	this := PublishProcessDefinitionPayload{}
	return &this
}

// GetConfirmed returns the Confirmed field value
func (o *PublishProcessDefinitionPayload) GetConfirmed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Confirmed
}

// GetConfirmedOk returns a tuple with the Confirmed field value
// and a boolean to check if the value has been set.
func (o *PublishProcessDefinitionPayload) GetConfirmedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confirmed, true
}

// SetConfirmed sets field value
func (o *PublishProcessDefinitionPayload) SetConfirmed(v bool) {
	o.Confirmed = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PublishProcessDefinitionPayload) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishProcessDefinitionPayload) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PublishProcessDefinitionPayload) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *PublishProcessDefinitionPayload) SetTags(v []string) {
	o.Tags = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *PublishProcessDefinitionPayload) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishProcessDefinitionPayload) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *PublishProcessDefinitionPayload) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *PublishProcessDefinitionPayload) SetLabel(v string) {
	o.Label = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *PublishProcessDefinitionPayload) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishProcessDefinitionPayload) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *PublishProcessDefinitionPayload) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *PublishProcessDefinitionPayload) SetComment(v string) {
	o.Comment = &v
}

func (o PublishProcessDefinitionPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishProcessDefinitionPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["confirmed"] = o.Confirmed
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

func (o *PublishProcessDefinitionPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"confirmed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishProcessDefinitionPayload := _PublishProcessDefinitionPayload{}

	err = json.Unmarshal(data, &varPublishProcessDefinitionPayload)

	if err != nil {
		return err
	}

	*o = PublishProcessDefinitionPayload(varPublishProcessDefinitionPayload)

	return err
}

type NullablePublishProcessDefinitionPayload struct {
	value *PublishProcessDefinitionPayload
	isSet bool
}

func (v NullablePublishProcessDefinitionPayload) Get() *PublishProcessDefinitionPayload {
	return v.value
}

func (v *NullablePublishProcessDefinitionPayload) Set(val *PublishProcessDefinitionPayload) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishProcessDefinitionPayload) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishProcessDefinitionPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishProcessDefinitionPayload(val *PublishProcessDefinitionPayload) *NullablePublishProcessDefinitionPayload {
	return &NullablePublishProcessDefinitionPayload{value: val, isSet: true}
}

func (v NullablePublishProcessDefinitionPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishProcessDefinitionPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
