/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateEventIngestChannelPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEventIngestChannelPayload{}

// UpdateEventIngestChannelPayload struct for UpdateEventIngestChannelPayload
type UpdateEventIngestChannelPayload struct {
	Name                *string `json:"name,omitempty"`
	Description         *string `json:"description,omitempty"`
	Source              *string `json:"source,omitempty"`
	DefaultAction       *string `json:"default_action,omitempty"`
	DefaultResourceType *string `json:"default_resource_type,omitempty"`
	// Pass null to remove the transform.
	Transform NullableEventIngestTransform `json:"transform,omitempty"`
	// Pass null to remove signature verification.
	Signature NullableEventIngestSignatureConfig `json:"signature,omitempty"`
	Priority  *EventPriority                     `json:"priority,omitempty"`
	Enabled   *bool                              `json:"enabled,omitempty"`
	// Request rotation of the channel ingest token on update.
	RotateToken *bool `json:"rotate_token,omitempty"`
	// Request rotation of the HMAC signing secret on update.
	RotateSigningSecret *bool `json:"rotate_signing_secret,omitempty"`
}

// NewUpdateEventIngestChannelPayload instantiates a new UpdateEventIngestChannelPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEventIngestChannelPayload() *UpdateEventIngestChannelPayload {
	this := UpdateEventIngestChannelPayload{}
	return &this
}

// NewUpdateEventIngestChannelPayloadWithDefaults instantiates a new UpdateEventIngestChannelPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEventIngestChannelPayloadWithDefaults() *UpdateEventIngestChannelPayload {
	this := UpdateEventIngestChannelPayload{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateEventIngestChannelPayload) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateEventIngestChannelPayload) SetDescription(v string) {
	o.Description = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *UpdateEventIngestChannelPayload) SetSource(v string) {
	o.Source = &v
}

// GetDefaultAction returns the DefaultAction field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetDefaultAction() string {
	if o == nil || IsNil(o.DefaultAction) {
		var ret string
		return ret
	}
	return *o.DefaultAction
}

// GetDefaultActionOk returns a tuple with the DefaultAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetDefaultActionOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultAction) {
		return nil, false
	}
	return o.DefaultAction, true
}

// HasDefaultAction returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasDefaultAction() bool {
	if o != nil && !IsNil(o.DefaultAction) {
		return true
	}

	return false
}

// SetDefaultAction gets a reference to the given string and assigns it to the DefaultAction field.
func (o *UpdateEventIngestChannelPayload) SetDefaultAction(v string) {
	o.DefaultAction = &v
}

// GetDefaultResourceType returns the DefaultResourceType field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetDefaultResourceType() string {
	if o == nil || IsNil(o.DefaultResourceType) {
		var ret string
		return ret
	}
	return *o.DefaultResourceType
}

// GetDefaultResourceTypeOk returns a tuple with the DefaultResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetDefaultResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultResourceType) {
		return nil, false
	}
	return o.DefaultResourceType, true
}

// HasDefaultResourceType returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasDefaultResourceType() bool {
	if o != nil && !IsNil(o.DefaultResourceType) {
		return true
	}

	return false
}

// SetDefaultResourceType gets a reference to the given string and assigns it to the DefaultResourceType field.
func (o *UpdateEventIngestChannelPayload) SetDefaultResourceType(v string) {
	o.DefaultResourceType = &v
}

// GetTransform returns the Transform field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEventIngestChannelPayload) GetTransform() EventIngestTransform {
	if o == nil || IsNil(o.Transform.Get()) {
		var ret EventIngestTransform
		return ret
	}
	return *o.Transform.Get()
}

// GetTransformOk returns a tuple with the Transform field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEventIngestChannelPayload) GetTransformOk() (*EventIngestTransform, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transform.Get(), o.Transform.IsSet()
}

// HasTransform returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasTransform() bool {
	if o != nil && o.Transform.IsSet() {
		return true
	}

	return false
}

// SetTransform gets a reference to the given NullableEventIngestTransform and assigns it to the Transform field.
func (o *UpdateEventIngestChannelPayload) SetTransform(v EventIngestTransform) {
	o.Transform.Set(&v)
}

// SetTransformNil sets the value for Transform to be an explicit nil
func (o *UpdateEventIngestChannelPayload) SetTransformNil() {
	o.Transform.Set(nil)
}

// UnsetTransform ensures that no value is present for Transform, not even an explicit nil
func (o *UpdateEventIngestChannelPayload) UnsetTransform() {
	o.Transform.Unset()
}

// GetSignature returns the Signature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEventIngestChannelPayload) GetSignature() EventIngestSignatureConfig {
	if o == nil || IsNil(o.Signature.Get()) {
		var ret EventIngestSignatureConfig
		return ret
	}
	return *o.Signature.Get()
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEventIngestChannelPayload) GetSignatureOk() (*EventIngestSignatureConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Signature.Get(), o.Signature.IsSet()
}

// HasSignature returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasSignature() bool {
	if o != nil && o.Signature.IsSet() {
		return true
	}

	return false
}

// SetSignature gets a reference to the given NullableEventIngestSignatureConfig and assigns it to the Signature field.
func (o *UpdateEventIngestChannelPayload) SetSignature(v EventIngestSignatureConfig) {
	o.Signature.Set(&v)
}

// SetSignatureNil sets the value for Signature to be an explicit nil
func (o *UpdateEventIngestChannelPayload) SetSignatureNil() {
	o.Signature.Set(nil)
}

// UnsetSignature ensures that no value is present for Signature, not even an explicit nil
func (o *UpdateEventIngestChannelPayload) UnsetSignature() {
	o.Signature.Unset()
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetPriority() EventPriority {
	if o == nil || IsNil(o.Priority) {
		var ret EventPriority
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetPriorityOk() (*EventPriority, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given EventPriority and assigns it to the Priority field.
func (o *UpdateEventIngestChannelPayload) SetPriority(v EventPriority) {
	o.Priority = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *UpdateEventIngestChannelPayload) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetRotateToken returns the RotateToken field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetRotateToken() bool {
	if o == nil || IsNil(o.RotateToken) {
		var ret bool
		return ret
	}
	return *o.RotateToken
}

// GetRotateTokenOk returns a tuple with the RotateToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetRotateTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.RotateToken) {
		return nil, false
	}
	return o.RotateToken, true
}

// HasRotateToken returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasRotateToken() bool {
	if o != nil && !IsNil(o.RotateToken) {
		return true
	}

	return false
}

// SetRotateToken gets a reference to the given bool and assigns it to the RotateToken field.
func (o *UpdateEventIngestChannelPayload) SetRotateToken(v bool) {
	o.RotateToken = &v
}

// GetRotateSigningSecret returns the RotateSigningSecret field value if set, zero value otherwise.
func (o *UpdateEventIngestChannelPayload) GetRotateSigningSecret() bool {
	if o == nil || IsNil(o.RotateSigningSecret) {
		var ret bool
		return ret
	}
	return *o.RotateSigningSecret
}

// GetRotateSigningSecretOk returns a tuple with the RotateSigningSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventIngestChannelPayload) GetRotateSigningSecretOk() (*bool, bool) {
	if o == nil || IsNil(o.RotateSigningSecret) {
		return nil, false
	}
	return o.RotateSigningSecret, true
}

// HasRotateSigningSecret returns a boolean if a field has been set.
func (o *UpdateEventIngestChannelPayload) HasRotateSigningSecret() bool {
	if o != nil && !IsNil(o.RotateSigningSecret) {
		return true
	}

	return false
}

// SetRotateSigningSecret gets a reference to the given bool and assigns it to the RotateSigningSecret field.
func (o *UpdateEventIngestChannelPayload) SetRotateSigningSecret(v bool) {
	o.RotateSigningSecret = &v
}

func (o UpdateEventIngestChannelPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEventIngestChannelPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.DefaultAction) {
		toSerialize["default_action"] = o.DefaultAction
	}
	if !IsNil(o.DefaultResourceType) {
		toSerialize["default_resource_type"] = o.DefaultResourceType
	}
	if o.Transform.IsSet() {
		toSerialize["transform"] = o.Transform.Get()
	}
	if o.Signature.IsSet() {
		toSerialize["signature"] = o.Signature.Get()
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.RotateToken) {
		toSerialize["rotate_token"] = o.RotateToken
	}
	if !IsNil(o.RotateSigningSecret) {
		toSerialize["rotate_signing_secret"] = o.RotateSigningSecret
	}
	return toSerialize, nil
}

type NullableUpdateEventIngestChannelPayload struct {
	value *UpdateEventIngestChannelPayload
	isSet bool
}

func (v NullableUpdateEventIngestChannelPayload) Get() *UpdateEventIngestChannelPayload {
	return v.value
}

func (v *NullableUpdateEventIngestChannelPayload) Set(val *UpdateEventIngestChannelPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEventIngestChannelPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEventIngestChannelPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEventIngestChannelPayload(val *UpdateEventIngestChannelPayload) *NullableUpdateEventIngestChannelPayload {
	return &NullableUpdateEventIngestChannelPayload{value: val, isSet: true}
}

func (v NullableUpdateEventIngestChannelPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEventIngestChannelPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
