/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InteractionExecutionPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InteractionExecutionPayload{}

// InteractionExecutionPayload struct for InteractionExecutionPayload
type InteractionExecutionPayload struct {
	Data         interface{}                                  `json:"data,omitempty"`
	Config       *InteractionExecutionConfiguration           `json:"config,omitempty"`
	ResultSchema NullableInteractionUpdatePayloadResultSchema `json:"result_schema,omitempty"`
	Stream       *bool                                        `json:"stream,omitempty"`
	DoValidate   *bool                                        `json:"do_validate,omitempty"`
	Tags         []string                                     `json:"tags,omitempty"`
	Conversation interface{}                                  `json:"conversation,omitempty"`
	// The tools to be used in the execution
	ToolDefinitions []ToolDefinition `json:"tool_definitions,omitempty"`
	// The workflow related to this Interaction Run.
	Workflow *ExecutionRunWorkflow `json:"workflow,omitempty"`
	// Only used by ad-hoc interactions which defines the prompt in the execution payload itself These are temporary interactions using \"tmp:\" suffix.
	Prompts []InCodePrompt `json:"prompts,omitempty"`
	// Options for async completion and/or streaming LLM response chunks to Redis. Used by agent workflows for async activity completion and real-time streaming.
	AsyncCompletion *AsyncCompletionOptions `json:"asyncCompletion,omitempty"`
}

// NewInteractionExecutionPayload instantiates a new InteractionExecutionPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInteractionExecutionPayload() *InteractionExecutionPayload {
	this := InteractionExecutionPayload{}
	return &this
}

// NewInteractionExecutionPayloadWithDefaults instantiates a new InteractionExecutionPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInteractionExecutionPayloadWithDefaults() *InteractionExecutionPayload {
	this := InteractionExecutionPayload{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InteractionExecutionPayload) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InteractionExecutionPayload) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *InteractionExecutionPayload) SetData(v interface{}) {
	o.Data = v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetConfig() InteractionExecutionConfiguration {
	if o == nil || IsNil(o.Config) {
		var ret InteractionExecutionConfiguration
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetConfigOk() (*InteractionExecutionConfiguration, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given InteractionExecutionConfiguration and assigns it to the Config field.
func (o *InteractionExecutionPayload) SetConfig(v InteractionExecutionConfiguration) {
	o.Config = &v
}

// GetResultSchema returns the ResultSchema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InteractionExecutionPayload) GetResultSchema() InteractionUpdatePayloadResultSchema {
	if o == nil || IsNil(o.ResultSchema.Get()) {
		var ret InteractionUpdatePayloadResultSchema
		return ret
	}
	return *o.ResultSchema.Get()
}

// GetResultSchemaOk returns a tuple with the ResultSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InteractionExecutionPayload) GetResultSchemaOk() (*InteractionUpdatePayloadResultSchema, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultSchema.Get(), o.ResultSchema.IsSet()
}

// HasResultSchema returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasResultSchema() bool {
	if o != nil && o.ResultSchema.IsSet() {
		return true
	}

	return false
}

// SetResultSchema gets a reference to the given NullableInteractionUpdatePayloadResultSchema and assigns it to the ResultSchema field.
func (o *InteractionExecutionPayload) SetResultSchema(v InteractionUpdatePayloadResultSchema) {
	o.ResultSchema.Set(&v)
}

// SetResultSchemaNil sets the value for ResultSchema to be an explicit nil
func (o *InteractionExecutionPayload) SetResultSchemaNil() {
	o.ResultSchema.Set(nil)
}

// UnsetResultSchema ensures that no value is present for ResultSchema, not even an explicit nil
func (o *InteractionExecutionPayload) UnsetResultSchema() {
	o.ResultSchema.Unset()
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetStream() bool {
	if o == nil || IsNil(o.Stream) {
		var ret bool
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetStreamOk() (*bool, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given bool and assigns it to the Stream field.
func (o *InteractionExecutionPayload) SetStream(v bool) {
	o.Stream = &v
}

// GetDoValidate returns the DoValidate field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetDoValidate() bool {
	if o == nil || IsNil(o.DoValidate) {
		var ret bool
		return ret
	}
	return *o.DoValidate
}

// GetDoValidateOk returns a tuple with the DoValidate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetDoValidateOk() (*bool, bool) {
	if o == nil || IsNil(o.DoValidate) {
		return nil, false
	}
	return o.DoValidate, true
}

// HasDoValidate returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasDoValidate() bool {
	if o != nil && !IsNil(o.DoValidate) {
		return true
	}

	return false
}

// SetDoValidate gets a reference to the given bool and assigns it to the DoValidate field.
func (o *InteractionExecutionPayload) SetDoValidate(v bool) {
	o.DoValidate = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *InteractionExecutionPayload) SetTags(v []string) {
	o.Tags = v
}

// GetConversation returns the Conversation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InteractionExecutionPayload) GetConversation() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Conversation
}

// GetConversationOk returns a tuple with the Conversation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InteractionExecutionPayload) GetConversationOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Conversation) {
		return nil, false
	}
	return &o.Conversation, true
}

// HasConversation returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasConversation() bool {
	if o != nil && !IsNil(o.Conversation) {
		return true
	}

	return false
}

// SetConversation gets a reference to the given interface{} and assigns it to the Conversation field.
func (o *InteractionExecutionPayload) SetConversation(v interface{}) {
	o.Conversation = v
}

// GetToolDefinitions returns the ToolDefinitions field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetToolDefinitions() []ToolDefinition {
	if o == nil || IsNil(o.ToolDefinitions) {
		var ret []ToolDefinition
		return ret
	}
	return o.ToolDefinitions
}

// GetToolDefinitionsOk returns a tuple with the ToolDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetToolDefinitionsOk() ([]ToolDefinition, bool) {
	if o == nil || IsNil(o.ToolDefinitions) {
		return nil, false
	}
	return o.ToolDefinitions, true
}

// HasToolDefinitions returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasToolDefinitions() bool {
	if o != nil && !IsNil(o.ToolDefinitions) {
		return true
	}

	return false
}

// SetToolDefinitions gets a reference to the given []ToolDefinition and assigns it to the ToolDefinitions field.
func (o *InteractionExecutionPayload) SetToolDefinitions(v []ToolDefinition) {
	o.ToolDefinitions = v
}

// GetWorkflow returns the Workflow field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetWorkflow() ExecutionRunWorkflow {
	if o == nil || IsNil(o.Workflow) {
		var ret ExecutionRunWorkflow
		return ret
	}
	return *o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetWorkflowOk() (*ExecutionRunWorkflow, bool) {
	if o == nil || IsNil(o.Workflow) {
		return nil, false
	}
	return o.Workflow, true
}

// HasWorkflow returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasWorkflow() bool {
	if o != nil && !IsNil(o.Workflow) {
		return true
	}

	return false
}

// SetWorkflow gets a reference to the given ExecutionRunWorkflow and assigns it to the Workflow field.
func (o *InteractionExecutionPayload) SetWorkflow(v ExecutionRunWorkflow) {
	o.Workflow = &v
}

// GetPrompts returns the Prompts field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetPrompts() []InCodePrompt {
	if o == nil || IsNil(o.Prompts) {
		var ret []InCodePrompt
		return ret
	}
	return o.Prompts
}

// GetPromptsOk returns a tuple with the Prompts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetPromptsOk() ([]InCodePrompt, bool) {
	if o == nil || IsNil(o.Prompts) {
		return nil, false
	}
	return o.Prompts, true
}

// HasPrompts returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasPrompts() bool {
	if o != nil && !IsNil(o.Prompts) {
		return true
	}

	return false
}

// SetPrompts gets a reference to the given []InCodePrompt and assigns it to the Prompts field.
func (o *InteractionExecutionPayload) SetPrompts(v []InCodePrompt) {
	o.Prompts = v
}

// GetAsyncCompletion returns the AsyncCompletion field value if set, zero value otherwise.
func (o *InteractionExecutionPayload) GetAsyncCompletion() AsyncCompletionOptions {
	if o == nil || IsNil(o.AsyncCompletion) {
		var ret AsyncCompletionOptions
		return ret
	}
	return *o.AsyncCompletion
}

// GetAsyncCompletionOk returns a tuple with the AsyncCompletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InteractionExecutionPayload) GetAsyncCompletionOk() (*AsyncCompletionOptions, bool) {
	if o == nil || IsNil(o.AsyncCompletion) {
		return nil, false
	}
	return o.AsyncCompletion, true
}

// HasAsyncCompletion returns a boolean if a field has been set.
func (o *InteractionExecutionPayload) HasAsyncCompletion() bool {
	if o != nil && !IsNil(o.AsyncCompletion) {
		return true
	}

	return false
}

// SetAsyncCompletion gets a reference to the given AsyncCompletionOptions and assigns it to the AsyncCompletion field.
func (o *InteractionExecutionPayload) SetAsyncCompletion(v AsyncCompletionOptions) {
	o.AsyncCompletion = &v
}

func (o InteractionExecutionPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InteractionExecutionPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if o.ResultSchema.IsSet() {
		toSerialize["result_schema"] = o.ResultSchema.Get()
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if !IsNil(o.DoValidate) {
		toSerialize["do_validate"] = o.DoValidate
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Conversation != nil {
		toSerialize["conversation"] = o.Conversation
	}
	if !IsNil(o.ToolDefinitions) {
		toSerialize["tool_definitions"] = o.ToolDefinitions
	}
	if !IsNil(o.Workflow) {
		toSerialize["workflow"] = o.Workflow
	}
	if !IsNil(o.Prompts) {
		toSerialize["prompts"] = o.Prompts
	}
	if !IsNil(o.AsyncCompletion) {
		toSerialize["asyncCompletion"] = o.AsyncCompletion
	}
	return toSerialize, nil
}

type NullableInteractionExecutionPayload struct {
	value *InteractionExecutionPayload
	isSet bool
}

func (v NullableInteractionExecutionPayload) Get() *InteractionExecutionPayload {
	return v.value
}

func (v *NullableInteractionExecutionPayload) Set(val *InteractionExecutionPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableInteractionExecutionPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableInteractionExecutionPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInteractionExecutionPayload(val *InteractionExecutionPayload) *NullableInteractionExecutionPayload {
	return &NullableInteractionExecutionPayload{value: val, isSet: true}
}

func (v NullableInteractionExecutionPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInteractionExecutionPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
