/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConversationFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConversationFile{}

// ConversationFile Represents a file being processed in a conversation workflow.
type ConversationFile struct {
	// Unique ID for tracking this file (generated client-side)
	Id string `json:"id"`
	// Original filename
	Name string `json:"name"`
	// MIME type
	ContentType string `json:"content_type"`
	// Size in bytes
	Size float32 `json:"size"`
	// Current processing status
	Status FileProcessingStatus `json:"status"`
	// Artifact path (e.g., \"files/document.pdf\") - set after upload
	ArtifactPath *string `json:"artifact_path,omitempty"`
	// Full artifact reference URI (e.g., \"artifact:files/document.pdf\")
	Reference *string `json:"reference,omitempty"`
	// Path to extracted text markdown (e.g., \"files/document.pdf.md\")
	MdPath *string `json:"md_path,omitempty"`
	// Whether text extraction completed successfully
	TextExtracted *bool `json:"text_extracted,omitempty"`
	// Error message if status is ERROR
	Error *string `json:"error,omitempty"`
	// Timestamp when upload started
	StartedAt float32 `json:"started_at"`
	// Timestamp when processing completed
	CompletedAt *float32 `json:"completed_at,omitempty"`
}

type _ConversationFile ConversationFile

// NewConversationFile instantiates a new ConversationFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConversationFile(id string, name string, contentType string, size float32, status FileProcessingStatus, startedAt float32) *ConversationFile {
	this := ConversationFile{}
	this.Id = id
	this.Name = name
	this.ContentType = contentType
	this.Size = size
	this.Status = status
	this.StartedAt = startedAt
	return &this
}

// NewConversationFileWithDefaults instantiates a new ConversationFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConversationFileWithDefaults() *ConversationFile {
	this := ConversationFile{}
	return &this
}

// GetId returns the Id field value
func (o *ConversationFile) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConversationFile) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ConversationFile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConversationFile) SetName(v string) {
	o.Name = v
}

// GetContentType returns the ContentType field value
func (o *ConversationFile) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *ConversationFile) SetContentType(v string) {
	o.ContentType = v
}

// GetSize returns the Size field value
func (o *ConversationFile) GetSize() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetSizeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ConversationFile) SetSize(v float32) {
	o.Size = v
}

// GetStatus returns the Status field value
func (o *ConversationFile) GetStatus() FileProcessingStatus {
	if o == nil {
		var ret FileProcessingStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetStatusOk() (*FileProcessingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConversationFile) SetStatus(v FileProcessingStatus) {
	o.Status = v
}

// GetArtifactPath returns the ArtifactPath field value if set, zero value otherwise.
func (o *ConversationFile) GetArtifactPath() string {
	if o == nil || IsNil(o.ArtifactPath) {
		var ret string
		return ret
	}
	return *o.ArtifactPath
}

// GetArtifactPathOk returns a tuple with the ArtifactPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetArtifactPathOk() (*string, bool) {
	if o == nil || IsNil(o.ArtifactPath) {
		return nil, false
	}
	return o.ArtifactPath, true
}

// HasArtifactPath returns a boolean if a field has been set.
func (o *ConversationFile) HasArtifactPath() bool {
	if o != nil && !IsNil(o.ArtifactPath) {
		return true
	}

	return false
}

// SetArtifactPath gets a reference to the given string and assigns it to the ArtifactPath field.
func (o *ConversationFile) SetArtifactPath(v string) {
	o.ArtifactPath = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *ConversationFile) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *ConversationFile) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *ConversationFile) SetReference(v string) {
	o.Reference = &v
}

// GetMdPath returns the MdPath field value if set, zero value otherwise.
func (o *ConversationFile) GetMdPath() string {
	if o == nil || IsNil(o.MdPath) {
		var ret string
		return ret
	}
	return *o.MdPath
}

// GetMdPathOk returns a tuple with the MdPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetMdPathOk() (*string, bool) {
	if o == nil || IsNil(o.MdPath) {
		return nil, false
	}
	return o.MdPath, true
}

// HasMdPath returns a boolean if a field has been set.
func (o *ConversationFile) HasMdPath() bool {
	if o != nil && !IsNil(o.MdPath) {
		return true
	}

	return false
}

// SetMdPath gets a reference to the given string and assigns it to the MdPath field.
func (o *ConversationFile) SetMdPath(v string) {
	o.MdPath = &v
}

// GetTextExtracted returns the TextExtracted field value if set, zero value otherwise.
func (o *ConversationFile) GetTextExtracted() bool {
	if o == nil || IsNil(o.TextExtracted) {
		var ret bool
		return ret
	}
	return *o.TextExtracted
}

// GetTextExtractedOk returns a tuple with the TextExtracted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetTextExtractedOk() (*bool, bool) {
	if o == nil || IsNil(o.TextExtracted) {
		return nil, false
	}
	return o.TextExtracted, true
}

// HasTextExtracted returns a boolean if a field has been set.
func (o *ConversationFile) HasTextExtracted() bool {
	if o != nil && !IsNil(o.TextExtracted) {
		return true
	}

	return false
}

// SetTextExtracted gets a reference to the given bool and assigns it to the TextExtracted field.
func (o *ConversationFile) SetTextExtracted(v bool) {
	o.TextExtracted = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ConversationFile) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ConversationFile) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ConversationFile) SetError(v string) {
	o.Error = &v
}

// GetStartedAt returns the StartedAt field value
func (o *ConversationFile) GetStartedAt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetStartedAtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *ConversationFile) SetStartedAt(v float32) {
	o.StartedAt = v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *ConversationFile) GetCompletedAt() float32 {
	if o == nil || IsNil(o.CompletedAt) {
		var ret float32
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationFile) GetCompletedAtOk() (*float32, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ConversationFile) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given float32 and assigns it to the CompletedAt field.
func (o *ConversationFile) SetCompletedAt(v float32) {
	o.CompletedAt = &v
}

func (o ConversationFile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConversationFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["content_type"] = o.ContentType
	toSerialize["size"] = o.Size
	toSerialize["status"] = o.Status
	if !IsNil(o.ArtifactPath) {
		toSerialize["artifact_path"] = o.ArtifactPath
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.MdPath) {
		toSerialize["md_path"] = o.MdPath
	}
	if !IsNil(o.TextExtracted) {
		toSerialize["text_extracted"] = o.TextExtracted
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["started_at"] = o.StartedAt
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}
	return toSerialize, nil
}

func (o *ConversationFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"content_type",
		"size",
		"status",
		"started_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConversationFile := _ConversationFile{}

	err = json.Unmarshal(data, &varConversationFile)

	if err != nil {
		return err
	}

	*o = ConversationFile(varConversationFile)

	return err
}

type NullableConversationFile struct {
	value *ConversationFile
	isSet bool
}

func (v NullableConversationFile) Get() *ConversationFile {
	return v.value
}

func (v *NullableConversationFile) Set(val *ConversationFile) {
	v.value = val
	v.isSet = true
}

func (v NullableConversationFile) IsSet() bool {
	return v.isSet
}

func (v *NullableConversationFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConversationFile(val *ConversationFile) *NullableConversationFile {
	return &NullableConversationFile{value: val, isSet: true}
}

func (v NullableConversationFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConversationFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
