/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateViewExperienceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateViewExperienceRequest{}

// CreateViewExperienceRequest struct for CreateViewExperienceRequest
type CreateViewExperienceRequest struct {
	Name        string                       `json:"name"`
	Enabled     *bool                        `json:"enabled,omitempty"`
	Layout      *ViewExperienceLayout        `json:"layout,omitempty"`
	Scope       *ViewExperienceScope         `json:"scope,omitempty"`
	Navigation  []ViewNavigationItem         `json:"navigation,omitempty"`
	Search      *ViewSearchConfiguration     `json:"search,omitempty"`
	Results     *ViewResultsConfiguration    `json:"results,omitempty"`
	Description string                       `json:"description"`
	Id          string                       `json:"id"`
	Version     *ViewExperienceSchemaVersion `json:"version,omitempty"`
}

type _CreateViewExperienceRequest CreateViewExperienceRequest

// NewCreateViewExperienceRequest instantiates a new CreateViewExperienceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateViewExperienceRequest(name string, description string, id string) *CreateViewExperienceRequest {
	this := CreateViewExperienceRequest{}
	this.Name = name
	this.Description = description
	this.Id = id
	return &this
}

// NewCreateViewExperienceRequestWithDefaults instantiates a new CreateViewExperienceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateViewExperienceRequestWithDefaults() *CreateViewExperienceRequest {
	this := CreateViewExperienceRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateViewExperienceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateViewExperienceRequest) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateViewExperienceRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetLayout returns the Layout field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetLayout() ViewExperienceLayout {
	if o == nil || IsNil(o.Layout) {
		var ret ViewExperienceLayout
		return ret
	}
	return *o.Layout
}

// GetLayoutOk returns a tuple with the Layout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetLayoutOk() (*ViewExperienceLayout, bool) {
	if o == nil || IsNil(o.Layout) {
		return nil, false
	}
	return o.Layout, true
}

// HasLayout returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasLayout() bool {
	if o != nil && !IsNil(o.Layout) {
		return true
	}

	return false
}

// SetLayout gets a reference to the given ViewExperienceLayout and assigns it to the Layout field.
func (o *CreateViewExperienceRequest) SetLayout(v ViewExperienceLayout) {
	o.Layout = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetScope() ViewExperienceScope {
	if o == nil || IsNil(o.Scope) {
		var ret ViewExperienceScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetScopeOk() (*ViewExperienceScope, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given ViewExperienceScope and assigns it to the Scope field.
func (o *CreateViewExperienceRequest) SetScope(v ViewExperienceScope) {
	o.Scope = &v
}

// GetNavigation returns the Navigation field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetNavigation() []ViewNavigationItem {
	if o == nil || IsNil(o.Navigation) {
		var ret []ViewNavigationItem
		return ret
	}
	return o.Navigation
}

// GetNavigationOk returns a tuple with the Navigation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetNavigationOk() ([]ViewNavigationItem, bool) {
	if o == nil || IsNil(o.Navigation) {
		return nil, false
	}
	return o.Navigation, true
}

// HasNavigation returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasNavigation() bool {
	if o != nil && !IsNil(o.Navigation) {
		return true
	}

	return false
}

// SetNavigation gets a reference to the given []ViewNavigationItem and assigns it to the Navigation field.
func (o *CreateViewExperienceRequest) SetNavigation(v []ViewNavigationItem) {
	o.Navigation = v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetSearch() ViewSearchConfiguration {
	if o == nil || IsNil(o.Search) {
		var ret ViewSearchConfiguration
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetSearchOk() (*ViewSearchConfiguration, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given ViewSearchConfiguration and assigns it to the Search field.
func (o *CreateViewExperienceRequest) SetSearch(v ViewSearchConfiguration) {
	o.Search = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetResults() ViewResultsConfiguration {
	if o == nil || IsNil(o.Results) {
		var ret ViewResultsConfiguration
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetResultsOk() (*ViewResultsConfiguration, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given ViewResultsConfiguration and assigns it to the Results field.
func (o *CreateViewExperienceRequest) SetResults(v ViewResultsConfiguration) {
	o.Results = &v
}

// GetDescription returns the Description field value
func (o *CreateViewExperienceRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateViewExperienceRequest) SetDescription(v string) {
	o.Description = v
}

// GetId returns the Id field value
func (o *CreateViewExperienceRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateViewExperienceRequest) SetId(v string) {
	o.Id = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CreateViewExperienceRequest) GetVersion() ViewExperienceSchemaVersion {
	if o == nil || IsNil(o.Version) {
		var ret ViewExperienceSchemaVersion
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateViewExperienceRequest) GetVersionOk() (*ViewExperienceSchemaVersion, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CreateViewExperienceRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given ViewExperienceSchemaVersion and assigns it to the Version field.
func (o *CreateViewExperienceRequest) SetVersion(v ViewExperienceSchemaVersion) {
	o.Version = &v
}

func (o CreateViewExperienceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateViewExperienceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Layout) {
		toSerialize["layout"] = o.Layout
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.Navigation) {
		toSerialize["navigation"] = o.Navigation
	}
	if !IsNil(o.Search) {
		toSerialize["search"] = o.Search
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	toSerialize["description"] = o.Description
	toSerialize["id"] = o.Id
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *CreateViewExperienceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateViewExperienceRequest := _CreateViewExperienceRequest{}

	err = json.Unmarshal(data, &varCreateViewExperienceRequest)

	if err != nil {
		return err
	}

	*o = CreateViewExperienceRequest(varCreateViewExperienceRequest)

	return err
}

type NullableCreateViewExperienceRequest struct {
	value *CreateViewExperienceRequest
	isSet bool
}

func (v NullableCreateViewExperienceRequest) Get() *CreateViewExperienceRequest {
	return v.value
}

func (v *NullableCreateViewExperienceRequest) Set(val *CreateViewExperienceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateViewExperienceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateViewExperienceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateViewExperienceRequest(val *CreateViewExperienceRequest) *NullableCreateViewExperienceRequest {
	return &NullableCreateViewExperienceRequest{value: val, isSet: true}
}

func (v NullableCreateViewExperienceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateViewExperienceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
