/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260905.011013Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AppVersionGitSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppVersionGitSource{}

// AppVersionGitSource struct for AppVersionGitSource
type AppVersionGitSource struct {
	Url    *string `json:"url,omitempty"`
	Remote *string `json:"remote,omitempty"`
	// The source ref that should be used to reproduce this version. Immutable app versions use the exact commit SHA rather than a mutable branch or tag.
	Ref         *string               `json:"ref,omitempty"`
	RefType     *AppVersionGitRefType `json:"ref_type,omitempty"`
	Branch      *string               `json:"branch,omitempty"`
	Tag         *string               `json:"tag,omitempty"`
	Commit      *string               `json:"commit,omitempty"`
	Dirty       *bool                 `json:"dirty,omitempty"`
	Pushed      *bool                 `json:"pushed,omitempty"`
	PushWarning *string               `json:"push_warning,omitempty"`
}

// NewAppVersionGitSource instantiates a new AppVersionGitSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppVersionGitSource() *AppVersionGitSource {
	this := AppVersionGitSource{}
	return &this
}

// NewAppVersionGitSourceWithDefaults instantiates a new AppVersionGitSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppVersionGitSourceWithDefaults() *AppVersionGitSource {
	this := AppVersionGitSource{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AppVersionGitSource) SetUrl(v string) {
	o.Url = &v
}

// GetRemote returns the Remote field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetRemote() string {
	if o == nil || IsNil(o.Remote) {
		var ret string
		return ret
	}
	return *o.Remote
}

// GetRemoteOk returns a tuple with the Remote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetRemoteOk() (*string, bool) {
	if o == nil || IsNil(o.Remote) {
		return nil, false
	}
	return o.Remote, true
}

// HasRemote returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasRemote() bool {
	if o != nil && !IsNil(o.Remote) {
		return true
	}

	return false
}

// SetRemote gets a reference to the given string and assigns it to the Remote field.
func (o *AppVersionGitSource) SetRemote(v string) {
	o.Remote = &v
}

// GetRef returns the Ref field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetRef() string {
	if o == nil || IsNil(o.Ref) {
		var ret string
		return ret
	}
	return *o.Ref
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetRefOk() (*string, bool) {
	if o == nil || IsNil(o.Ref) {
		return nil, false
	}
	return o.Ref, true
}

// HasRef returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasRef() bool {
	if o != nil && !IsNil(o.Ref) {
		return true
	}

	return false
}

// SetRef gets a reference to the given string and assigns it to the Ref field.
func (o *AppVersionGitSource) SetRef(v string) {
	o.Ref = &v
}

// GetRefType returns the RefType field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetRefType() AppVersionGitRefType {
	if o == nil || IsNil(o.RefType) {
		var ret AppVersionGitRefType
		return ret
	}
	return *o.RefType
}

// GetRefTypeOk returns a tuple with the RefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetRefTypeOk() (*AppVersionGitRefType, bool) {
	if o == nil || IsNil(o.RefType) {
		return nil, false
	}
	return o.RefType, true
}

// HasRefType returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasRefType() bool {
	if o != nil && !IsNil(o.RefType) {
		return true
	}

	return false
}

// SetRefType gets a reference to the given AppVersionGitRefType and assigns it to the RefType field.
func (o *AppVersionGitSource) SetRefType(v AppVersionGitRefType) {
	o.RefType = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *AppVersionGitSource) SetBranch(v string) {
	o.Branch = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *AppVersionGitSource) SetTag(v string) {
	o.Tag = &v
}

// GetCommit returns the Commit field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetCommit() string {
	if o == nil || IsNil(o.Commit) {
		var ret string
		return ret
	}
	return *o.Commit
}

// GetCommitOk returns a tuple with the Commit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetCommitOk() (*string, bool) {
	if o == nil || IsNil(o.Commit) {
		return nil, false
	}
	return o.Commit, true
}

// HasCommit returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasCommit() bool {
	if o != nil && !IsNil(o.Commit) {
		return true
	}

	return false
}

// SetCommit gets a reference to the given string and assigns it to the Commit field.
func (o *AppVersionGitSource) SetCommit(v string) {
	o.Commit = &v
}

// GetDirty returns the Dirty field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetDirty() bool {
	if o == nil || IsNil(o.Dirty) {
		var ret bool
		return ret
	}
	return *o.Dirty
}

// GetDirtyOk returns a tuple with the Dirty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetDirtyOk() (*bool, bool) {
	if o == nil || IsNil(o.Dirty) {
		return nil, false
	}
	return o.Dirty, true
}

// HasDirty returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasDirty() bool {
	if o != nil && !IsNil(o.Dirty) {
		return true
	}

	return false
}

// SetDirty gets a reference to the given bool and assigns it to the Dirty field.
func (o *AppVersionGitSource) SetDirty(v bool) {
	o.Dirty = &v
}

// GetPushed returns the Pushed field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetPushed() bool {
	if o == nil || IsNil(o.Pushed) {
		var ret bool
		return ret
	}
	return *o.Pushed
}

// GetPushedOk returns a tuple with the Pushed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetPushedOk() (*bool, bool) {
	if o == nil || IsNil(o.Pushed) {
		return nil, false
	}
	return o.Pushed, true
}

// HasPushed returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasPushed() bool {
	if o != nil && !IsNil(o.Pushed) {
		return true
	}

	return false
}

// SetPushed gets a reference to the given bool and assigns it to the Pushed field.
func (o *AppVersionGitSource) SetPushed(v bool) {
	o.Pushed = &v
}

// GetPushWarning returns the PushWarning field value if set, zero value otherwise.
func (o *AppVersionGitSource) GetPushWarning() string {
	if o == nil || IsNil(o.PushWarning) {
		var ret string
		return ret
	}
	return *o.PushWarning
}

// GetPushWarningOk returns a tuple with the PushWarning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppVersionGitSource) GetPushWarningOk() (*string, bool) {
	if o == nil || IsNil(o.PushWarning) {
		return nil, false
	}
	return o.PushWarning, true
}

// HasPushWarning returns a boolean if a field has been set.
func (o *AppVersionGitSource) HasPushWarning() bool {
	if o != nil && !IsNil(o.PushWarning) {
		return true
	}

	return false
}

// SetPushWarning gets a reference to the given string and assigns it to the PushWarning field.
func (o *AppVersionGitSource) SetPushWarning(v string) {
	o.PushWarning = &v
}

func (o AppVersionGitSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppVersionGitSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Remote) {
		toSerialize["remote"] = o.Remote
	}
	if !IsNil(o.Ref) {
		toSerialize["ref"] = o.Ref
	}
	if !IsNil(o.RefType) {
		toSerialize["ref_type"] = o.RefType
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Commit) {
		toSerialize["commit"] = o.Commit
	}
	if !IsNil(o.Dirty) {
		toSerialize["dirty"] = o.Dirty
	}
	if !IsNil(o.Pushed) {
		toSerialize["pushed"] = o.Pushed
	}
	if !IsNil(o.PushWarning) {
		toSerialize["push_warning"] = o.PushWarning
	}
	return toSerialize, nil
}

type NullableAppVersionGitSource struct {
	value *AppVersionGitSource
	isSet bool
}

func (v NullableAppVersionGitSource) Get() *AppVersionGitSource {
	return v.value
}

func (v *NullableAppVersionGitSource) Set(val *AppVersionGitSource) {
	v.value = val
	v.isSet = true
}

func (v NullableAppVersionGitSource) IsSet() bool {
	return v.isSet
}

func (v *NullableAppVersionGitSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppVersionGitSource(val *AppVersionGitSource) *NullableAppVersionGitSource {
	return &NullableAppVersionGitSource{value: val, isSet: true}
}

func (v NullableAppVersionGitSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppVersionGitSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
