/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OAuthRegistrationSource the model 'OAuthRegistrationSource'
type OAuthRegistrationSource string

// List of OAuthRegistrationSource
const (
	OAUTHREGISTRATIONSOURCE_ADMIN                    OAuthRegistrationSource = "admin"
	OAUTHREGISTRATIONSOURCE_DYNAMIC                  OAuthRegistrationSource = "dynamic"
	OAUTHREGISTRATIONSOURCE_UNKNOWN_DEFAULT_OPEN_API OAuthRegistrationSource = "unknown_default_open_api"
)

// All allowed values of OAuthRegistrationSource enum
var AllowedOAuthRegistrationSourceEnumValues = []OAuthRegistrationSource{
	"admin",
	"dynamic",
	"unknown_default_open_api",
}

func (v *OAuthRegistrationSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OAuthRegistrationSource(value)
	for _, existing := range AllowedOAuthRegistrationSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = OAUTHREGISTRATIONSOURCE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewOAuthRegistrationSourceFromValue returns a pointer to a valid OAuthRegistrationSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOAuthRegistrationSourceFromValue(v string) (*OAuthRegistrationSource, error) {
	ev := OAuthRegistrationSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OAuthRegistrationSource: valid values are %v", v, AllowedOAuthRegistrationSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OAuthRegistrationSource) IsValid() bool {
	for _, existing := range AllowedOAuthRegistrationSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OAuthRegistrationSource value
func (v OAuthRegistrationSource) Ptr() *OAuthRegistrationSource {
	return &v
}

type NullableOAuthRegistrationSource struct {
	value *OAuthRegistrationSource
	isSet bool
}

func (v NullableOAuthRegistrationSource) Get() *OAuthRegistrationSource {
	return v.value
}

func (v *NullableOAuthRegistrationSource) Set(val *OAuthRegistrationSource) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthRegistrationSource) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthRegistrationSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthRegistrationSource(val *OAuthRegistrationSource) *NullableOAuthRegistrationSource {
	return &NullableOAuthRegistrationSource{value: val, isSet: true}
}

func (v NullableOAuthRegistrationSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthRegistrationSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
