/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ParallelCollectMode the model 'ParallelCollectMode'
type ParallelCollectMode string

// List of ParallelCollectMode
const (
	PARALLELCOLLECTMODE_ARRAY                    ParallelCollectMode = "array"
	PARALLELCOLLECTMODE_UNKNOWN_DEFAULT_OPEN_API ParallelCollectMode = "unknown_default_open_api"
)

// All allowed values of ParallelCollectMode enum
var AllowedParallelCollectModeEnumValues = []ParallelCollectMode{
	"array",
	"unknown_default_open_api",
}

func (v *ParallelCollectMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ParallelCollectMode(value)
	for _, existing := range AllowedParallelCollectModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = PARALLELCOLLECTMODE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewParallelCollectModeFromValue returns a pointer to a valid ParallelCollectMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewParallelCollectModeFromValue(v string) (*ParallelCollectMode, error) {
	ev := ParallelCollectMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ParallelCollectMode: valid values are %v", v, AllowedParallelCollectModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ParallelCollectMode) IsValid() bool {
	for _, existing := range AllowedParallelCollectModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ParallelCollectMode value
func (v ParallelCollectMode) Ptr() *ParallelCollectMode {
	return &v
}

type NullableParallelCollectMode struct {
	value *ParallelCollectMode
	isSet bool
}

func (v NullableParallelCollectMode) Get() *ParallelCollectMode {
	return v.value
}

func (v *NullableParallelCollectMode) Set(val *ParallelCollectMode) {
	v.value = val
	v.isSet = true
}

func (v NullableParallelCollectMode) IsSet() bool {
	return v.isSet
}

func (v *NullableParallelCollectMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParallelCollectMode(val *ParallelCollectMode) *NullableParallelCollectMode {
	return &NullableParallelCollectMode{value: val, isSet: true}
}

func (v NullableParallelCollectMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParallelCollectMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
