/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AdaptedTable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdaptedTable{}

// AdaptedTable The adapted table result format
type AdaptedTable struct {
	Comment *string                  `json:"comment,omitempty"`
	Data    []map[string]interface{} `json:"data"`
}

type _AdaptedTable AdaptedTable

// NewAdaptedTable instantiates a new AdaptedTable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdaptedTable(data []map[string]interface{}) *AdaptedTable {
	this := AdaptedTable{}
	this.Data = data
	return &this
}

// NewAdaptedTableWithDefaults instantiates a new AdaptedTable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdaptedTableWithDefaults() *AdaptedTable {
	this := AdaptedTable{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *AdaptedTable) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdaptedTable) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *AdaptedTable) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *AdaptedTable) SetComment(v string) {
	o.Comment = &v
}

// GetData returns the Data field value
func (o *AdaptedTable) GetData() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AdaptedTable) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AdaptedTable) SetData(v []map[string]interface{}) {
	o.Data = v
}

func (o AdaptedTable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdaptedTable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AdaptedTable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdaptedTable := _AdaptedTable{}

	err = json.Unmarshal(data, &varAdaptedTable)

	if err != nil {
		return err
	}

	*o = AdaptedTable(varAdaptedTable)

	return err
}

type NullableAdaptedTable struct {
	value *AdaptedTable
	isSet bool
}

func (v NullableAdaptedTable) Get() *AdaptedTable {
	return v.value
}

func (v *NullableAdaptedTable) Set(val *AdaptedTable) {
	v.value = val
	v.isSet = true
}

func (v NullableAdaptedTable) IsSet() bool {
	return v.isSet
}

func (v *NullableAdaptedTable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdaptedTable(val *AdaptedTable) *NullableAdaptedTable {
	return &NullableAdaptedTable{value: val, isSet: true}
}

func (v NullableAdaptedTable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdaptedTable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
