/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the QuotaStandingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaStandingResponse{}

// QuotaStandingResponse struct for QuotaStandingResponse
type QuotaStandingResponse struct {
	TenantId string `json:"tenant_id"`
	// False when the limiter store (Redis) was unavailable, so `api`/`admission` are empty because standing could not be read — NOT because there are no limits. Limiters fail open in this case.
	Available bool `json:"available"`
	// Deployment base tier (env QUOTA_BASE_TIER); `default` = the static limits stand.
	BaseTier string `json:"base_tier"`
	// Tier used to compute the API limits below: explicit account `quota_tier`, else account_type derived tier, else `base_tier` when the account tier could not be resolved.
	EffectiveTier string `json:"effective_tier"`
	// Per-resource API rate-limit standing (effective limits + current usage).
	Api                  []QuotaStandingResource        `json:"api"`
	Admission            QuotaStandingResponseAdmission `json:"admission"`
	Llm                  QuotaStandingResponseLlm       `json:"llm"`
	AdditionalProperties map[string]interface{}
}

type _QuotaStandingResponse QuotaStandingResponse

// NewQuotaStandingResponse instantiates a new QuotaStandingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaStandingResponse(tenantId string, available bool, baseTier string, effectiveTier string, api []QuotaStandingResource, admission QuotaStandingResponseAdmission, llm QuotaStandingResponseLlm) *QuotaStandingResponse {
	this := QuotaStandingResponse{}
	this.TenantId = tenantId
	this.Available = available
	this.BaseTier = baseTier
	this.EffectiveTier = effectiveTier
	this.Api = api
	this.Admission = admission
	this.Llm = llm
	return &this
}

// NewQuotaStandingResponseWithDefaults instantiates a new QuotaStandingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaStandingResponseWithDefaults() *QuotaStandingResponse {
	this := QuotaStandingResponse{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *QuotaStandingResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *QuotaStandingResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetAvailable returns the Available field value
func (o *QuotaStandingResponse) GetAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *QuotaStandingResponse) SetAvailable(v bool) {
	o.Available = v
}

// GetBaseTier returns the BaseTier field value
func (o *QuotaStandingResponse) GetBaseTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseTier
}

// GetBaseTierOk returns a tuple with the BaseTier field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetBaseTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseTier, true
}

// SetBaseTier sets field value
func (o *QuotaStandingResponse) SetBaseTier(v string) {
	o.BaseTier = v
}

// GetEffectiveTier returns the EffectiveTier field value
func (o *QuotaStandingResponse) GetEffectiveTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveTier
}

// GetEffectiveTierOk returns a tuple with the EffectiveTier field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetEffectiveTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveTier, true
}

// SetEffectiveTier sets field value
func (o *QuotaStandingResponse) SetEffectiveTier(v string) {
	o.EffectiveTier = v
}

// GetApi returns the Api field value
func (o *QuotaStandingResponse) GetApi() []QuotaStandingResource {
	if o == nil {
		var ret []QuotaStandingResource
		return ret
	}

	return o.Api
}

// GetApiOk returns a tuple with the Api field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetApiOk() ([]QuotaStandingResource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Api, true
}

// SetApi sets field value
func (o *QuotaStandingResponse) SetApi(v []QuotaStandingResource) {
	o.Api = v
}

// GetAdmission returns the Admission field value
func (o *QuotaStandingResponse) GetAdmission() QuotaStandingResponseAdmission {
	if o == nil {
		var ret QuotaStandingResponseAdmission
		return ret
	}

	return o.Admission
}

// GetAdmissionOk returns a tuple with the Admission field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetAdmissionOk() (*QuotaStandingResponseAdmission, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Admission, true
}

// SetAdmission sets field value
func (o *QuotaStandingResponse) SetAdmission(v QuotaStandingResponseAdmission) {
	o.Admission = v
}

// GetLlm returns the Llm field value
func (o *QuotaStandingResponse) GetLlm() QuotaStandingResponseLlm {
	if o == nil {
		var ret QuotaStandingResponseLlm
		return ret
	}

	return o.Llm
}

// GetLlmOk returns a tuple with the Llm field value
// and a boolean to check if the value has been set.
func (o *QuotaStandingResponse) GetLlmOk() (*QuotaStandingResponseLlm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Llm, true
}

// SetLlm sets field value
func (o *QuotaStandingResponse) SetLlm(v QuotaStandingResponseLlm) {
	o.Llm = v
}

func (o QuotaStandingResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaStandingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["available"] = o.Available
	toSerialize["base_tier"] = o.BaseTier
	toSerialize["effective_tier"] = o.EffectiveTier
	toSerialize["api"] = o.Api
	toSerialize["admission"] = o.Admission
	toSerialize["llm"] = o.Llm

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuotaStandingResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"available",
		"base_tier",
		"effective_tier",
		"api",
		"admission",
		"llm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuotaStandingResponse := _QuotaStandingResponse{}

	err = json.Unmarshal(data, &varQuotaStandingResponse)

	if err != nil {
		return err
	}

	*o = QuotaStandingResponse(varQuotaStandingResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "available")
		delete(additionalProperties, "base_tier")
		delete(additionalProperties, "effective_tier")
		delete(additionalProperties, "api")
		delete(additionalProperties, "admission")
		delete(additionalProperties, "llm")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuotaStandingResponse struct {
	value *QuotaStandingResponse
	isSet bool
}

func (v NullableQuotaStandingResponse) Get() *QuotaStandingResponse {
	return v.value
}

func (v *NullableQuotaStandingResponse) Set(val *QuotaStandingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaStandingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaStandingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaStandingResponse(val *QuotaStandingResponse) *NullableQuotaStandingResponse {
	return &NullableQuotaStandingResponse{value: val, isSet: true}
}

func (v NullableQuotaStandingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaStandingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
