/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// LlmCallType Types of LLM calls in a conversation
type LlmCallType string

// List of LlmCallType
const (
	LLMCALLTYPE_START                    LlmCallType = "start"
	LLMCALLTYPE_RESUME_TOOLS             LlmCallType = "resume_tools"
	LLMCALLTYPE_RESUME_USER              LlmCallType = "resume_user"
	LLMCALLTYPE_CHECKPOINT               LlmCallType = "checkpoint"
	LLMCALLTYPE_NESTED_INTERACTION       LlmCallType = "nested_interaction"
	LLMCALLTYPE_UNKNOWN_DEFAULT_OPEN_API LlmCallType = "unknown_default_open_api"
)

// All allowed values of LlmCallType enum
var AllowedLlmCallTypeEnumValues = []LlmCallType{
	"start",
	"resume_tools",
	"resume_user",
	"checkpoint",
	"nested_interaction",
	"unknown_default_open_api",
}

func (v *LlmCallType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LlmCallType(value)
	for _, existing := range AllowedLlmCallTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = LLMCALLTYPE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewLlmCallTypeFromValue returns a pointer to a valid LlmCallType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLlmCallTypeFromValue(v string) (*LlmCallType, error) {
	ev := LlmCallType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LlmCallType: valid values are %v", v, AllowedLlmCallTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LlmCallType) IsValid() bool {
	for _, existing := range AllowedLlmCallTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LlmCallType value
func (v LlmCallType) Ptr() *LlmCallType {
	return &v
}

type NullableLlmCallType struct {
	value *LlmCallType
	isSet bool
}

func (v NullableLlmCallType) Get() *LlmCallType {
	return v.value
}

func (v *NullableLlmCallType) Set(val *LlmCallType) {
	v.value = val
	v.isSet = true
}

func (v NullableLlmCallType) IsSet() bool {
	return v.isSet
}

func (v *NullableLlmCallType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLlmCallType(val *LlmCallType) *NullableLlmCallType {
	return &NullableLlmCallType{value: val, isSet: true}
}

func (v NullableLlmCallType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLlmCallType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
