/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AsyncExecutionPayload - struct for AsyncExecutionPayload
type AsyncExecutionPayload struct {
	AsyncConversationExecutionPayload *AsyncConversationExecutionPayload
	AsyncInteractionExecutionPayload  *AsyncInteractionExecutionPayload
}

// AsyncConversationExecutionPayloadAsAsyncExecutionPayload is a convenience function that returns AsyncConversationExecutionPayload wrapped in AsyncExecutionPayload
func AsyncConversationExecutionPayloadAsAsyncExecutionPayload(v *AsyncConversationExecutionPayload) AsyncExecutionPayload {
	return AsyncExecutionPayload{
		AsyncConversationExecutionPayload: v,
	}
}

// AsyncInteractionExecutionPayloadAsAsyncExecutionPayload is a convenience function that returns AsyncInteractionExecutionPayload wrapped in AsyncExecutionPayload
func AsyncInteractionExecutionPayloadAsAsyncExecutionPayload(v *AsyncInteractionExecutionPayload) AsyncExecutionPayload {
	return AsyncExecutionPayload{
		AsyncInteractionExecutionPayload: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *AsyncExecutionPayload) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AsyncConversationExecutionPayload
	err = newStrictDecoder(data).Decode(&dst.AsyncConversationExecutionPayload)
	if err == nil {
		jsonAsyncConversationExecutionPayload, _ := json.Marshal(dst.AsyncConversationExecutionPayload)
		if string(jsonAsyncConversationExecutionPayload) == "{}" { // empty struct
			dst.AsyncConversationExecutionPayload = nil
		} else {
			if err = validator.Validate(dst.AsyncConversationExecutionPayload); err != nil {
				dst.AsyncConversationExecutionPayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.AsyncConversationExecutionPayload = nil
	}

	// try to unmarshal data into AsyncInteractionExecutionPayload
	err = newStrictDecoder(data).Decode(&dst.AsyncInteractionExecutionPayload)
	if err == nil {
		jsonAsyncInteractionExecutionPayload, _ := json.Marshal(dst.AsyncInteractionExecutionPayload)
		if string(jsonAsyncInteractionExecutionPayload) == "{}" { // empty struct
			dst.AsyncInteractionExecutionPayload = nil
		} else {
			if err = validator.Validate(dst.AsyncInteractionExecutionPayload); err != nil {
				dst.AsyncInteractionExecutionPayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.AsyncInteractionExecutionPayload = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AsyncConversationExecutionPayload = nil
		dst.AsyncInteractionExecutionPayload = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AsyncExecutionPayload)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AsyncExecutionPayload)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AsyncExecutionPayload) MarshalJSON() ([]byte, error) {
	if src.AsyncConversationExecutionPayload != nil {
		return json.Marshal(&src.AsyncConversationExecutionPayload)
	}

	if src.AsyncInteractionExecutionPayload != nil {
		return json.Marshal(&src.AsyncInteractionExecutionPayload)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AsyncExecutionPayload) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AsyncConversationExecutionPayload != nil {
		return obj.AsyncConversationExecutionPayload
	}

	if obj.AsyncInteractionExecutionPayload != nil {
		return obj.AsyncInteractionExecutionPayload
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AsyncExecutionPayload) GetActualInstanceValue() interface{} {
	if obj.AsyncConversationExecutionPayload != nil {
		return *obj.AsyncConversationExecutionPayload
	}

	if obj.AsyncInteractionExecutionPayload != nil {
		return *obj.AsyncInteractionExecutionPayload
	}

	// all schemas are nil
	return nil
}

type NullableAsyncExecutionPayload struct {
	value *AsyncExecutionPayload
	isSet bool
}

func (v NullableAsyncExecutionPayload) Get() *AsyncExecutionPayload {
	return v.value
}

func (v *NullableAsyncExecutionPayload) Set(val *AsyncExecutionPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableAsyncExecutionPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableAsyncExecutionPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAsyncExecutionPayload(val *AsyncExecutionPayload) *NullableAsyncExecutionPayload {
	return &NullableAsyncExecutionPayload{value: val, isSet: true}
}

func (v NullableAsyncExecutionPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAsyncExecutionPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
