/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// InteractionStatus the model 'InteractionStatus'
type InteractionStatus string

// List of InteractionStatus
const (
	INTERACTIONSTATUS_DRAFT                    InteractionStatus = "draft"
	INTERACTIONSTATUS_PUBLISHED                InteractionStatus = "published"
	INTERACTIONSTATUS_ARCHIVED                 InteractionStatus = "archived"
	INTERACTIONSTATUS_CODE                     InteractionStatus = "code"
	INTERACTIONSTATUS_UNKNOWN                  InteractionStatus = "unknown"
	INTERACTIONSTATUS_UNKNOWN_DEFAULT_OPEN_API InteractionStatus = "unknown_default_open_api"
)

// All allowed values of InteractionStatus enum
var AllowedInteractionStatusEnumValues = []InteractionStatus{
	"draft",
	"published",
	"archived",
	"code",
	"unknown",
	"unknown_default_open_api",
}

func (v *InteractionStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := InteractionStatus(value)
	for _, existing := range AllowedInteractionStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = INTERACTIONSTATUS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewInteractionStatusFromValue returns a pointer to a valid InteractionStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewInteractionStatusFromValue(v string) (*InteractionStatus, error) {
	ev := InteractionStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for InteractionStatus: valid values are %v", v, AllowedInteractionStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v InteractionStatus) IsValid() bool {
	for _, existing := range AllowedInteractionStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to InteractionStatus value
func (v InteractionStatus) Ptr() *InteractionStatus {
	return &v
}

type NullableInteractionStatus struct {
	value *InteractionStatus
	isSet bool
}

func (v NullableInteractionStatus) Get() *InteractionStatus {
	return v.value
}

func (v *NullableInteractionStatus) Set(val *InteractionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableInteractionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableInteractionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInteractionStatus(val *InteractionStatus) *NullableInteractionStatus {
	return &NullableInteractionStatus{value: val, isSet: true}
}

func (v NullableInteractionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInteractionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
