/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260807.073259Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AppManifestPreviewScreenshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppManifestPreviewScreenshot{}

// AppManifestPreviewScreenshot Optional preview screenshot for the app-management UI, captured by the builder during a build/QA run. Resolved client-side from the owning agent run's artifact storage, so it carries both the run id and the artifact path.
type AppManifestPreviewScreenshot struct {
	// Agent run id whose artifact storage holds the screenshot.
	AgentRunId string `json:"agent_run_id"`
	// Artifact path within that storage, e.g. \"preview-checks/app-preview-<ts>.png\".
	Artifact string `json:"artifact"`
}

type _AppManifestPreviewScreenshot AppManifestPreviewScreenshot

// NewAppManifestPreviewScreenshot instantiates a new AppManifestPreviewScreenshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppManifestPreviewScreenshot(agentRunId string, artifact string) *AppManifestPreviewScreenshot {
	this := AppManifestPreviewScreenshot{}
	this.AgentRunId = agentRunId
	this.Artifact = artifact
	return &this
}

// NewAppManifestPreviewScreenshotWithDefaults instantiates a new AppManifestPreviewScreenshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppManifestPreviewScreenshotWithDefaults() *AppManifestPreviewScreenshot {
	this := AppManifestPreviewScreenshot{}
	return &this
}

// GetAgentRunId returns the AgentRunId field value
func (o *AppManifestPreviewScreenshot) GetAgentRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentRunId
}

// GetAgentRunIdOk returns a tuple with the AgentRunId field value
// and a boolean to check if the value has been set.
func (o *AppManifestPreviewScreenshot) GetAgentRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentRunId, true
}

// SetAgentRunId sets field value
func (o *AppManifestPreviewScreenshot) SetAgentRunId(v string) {
	o.AgentRunId = v
}

// GetArtifact returns the Artifact field value
func (o *AppManifestPreviewScreenshot) GetArtifact() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Artifact
}

// GetArtifactOk returns a tuple with the Artifact field value
// and a boolean to check if the value has been set.
func (o *AppManifestPreviewScreenshot) GetArtifactOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Artifact, true
}

// SetArtifact sets field value
func (o *AppManifestPreviewScreenshot) SetArtifact(v string) {
	o.Artifact = v
}

func (o AppManifestPreviewScreenshot) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppManifestPreviewScreenshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_run_id"] = o.AgentRunId
	toSerialize["artifact"] = o.Artifact
	return toSerialize, nil
}

func (o *AppManifestPreviewScreenshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_run_id",
		"artifact",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppManifestPreviewScreenshot := _AppManifestPreviewScreenshot{}

	err = json.Unmarshal(data, &varAppManifestPreviewScreenshot)

	if err != nil {
		return err
	}

	*o = AppManifestPreviewScreenshot(varAppManifestPreviewScreenshot)

	return err
}

type NullableAppManifestPreviewScreenshot struct {
	value *AppManifestPreviewScreenshot
	isSet bool
}

func (v NullableAppManifestPreviewScreenshot) Get() *AppManifestPreviewScreenshot {
	return v.value
}

func (v *NullableAppManifestPreviewScreenshot) Set(val *AppManifestPreviewScreenshot) {
	v.value = val
	v.isSet = true
}

func (v NullableAppManifestPreviewScreenshot) IsSet() bool {
	return v.isSet
}

func (v *NullableAppManifestPreviewScreenshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppManifestPreviewScreenshot(val *AppManifestPreviewScreenshot) *NullableAppManifestPreviewScreenshot {
	return &NullableAppManifestPreviewScreenshot{value: val, isSet: true}
}

func (v NullableAppManifestPreviewScreenshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppManifestPreviewScreenshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
