/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260826.064249Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ViewSelectionConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewSelectionConfiguration{}

// ViewSelectionConfiguration Client-side selection behavior for normalized View hits.
type ViewSelectionConfiguration struct {
	Mode ViewSelectionMode `json:"mode"`
	// Select-all applies to the currently rendered page.
	SelectAll *string `json:"select_all,omitempty"`
}

type _ViewSelectionConfiguration ViewSelectionConfiguration

// NewViewSelectionConfiguration instantiates a new ViewSelectionConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewSelectionConfiguration(mode ViewSelectionMode) *ViewSelectionConfiguration {
	this := ViewSelectionConfiguration{}
	this.Mode = mode
	return &this
}

// NewViewSelectionConfigurationWithDefaults instantiates a new ViewSelectionConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewSelectionConfigurationWithDefaults() *ViewSelectionConfiguration {
	this := ViewSelectionConfiguration{}
	return &this
}

// GetMode returns the Mode field value
func (o *ViewSelectionConfiguration) GetMode() ViewSelectionMode {
	if o == nil {
		var ret ViewSelectionMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ViewSelectionConfiguration) GetModeOk() (*ViewSelectionMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ViewSelectionConfiguration) SetMode(v ViewSelectionMode) {
	o.Mode = v
}

// GetSelectAll returns the SelectAll field value if set, zero value otherwise.
func (o *ViewSelectionConfiguration) GetSelectAll() string {
	if o == nil || IsNil(o.SelectAll) {
		var ret string
		return ret
	}
	return *o.SelectAll
}

// GetSelectAllOk returns a tuple with the SelectAll field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewSelectionConfiguration) GetSelectAllOk() (*string, bool) {
	if o == nil || IsNil(o.SelectAll) {
		return nil, false
	}
	return o.SelectAll, true
}

// HasSelectAll returns a boolean if a field has been set.
func (o *ViewSelectionConfiguration) HasSelectAll() bool {
	if o != nil && !IsNil(o.SelectAll) {
		return true
	}

	return false
}

// SetSelectAll gets a reference to the given string and assigns it to the SelectAll field.
func (o *ViewSelectionConfiguration) SetSelectAll(v string) {
	o.SelectAll = &v
}

func (o ViewSelectionConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewSelectionConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	if !IsNil(o.SelectAll) {
		toSerialize["select_all"] = o.SelectAll
	}
	return toSerialize, nil
}

func (o *ViewSelectionConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViewSelectionConfiguration := _ViewSelectionConfiguration{}

	err = json.Unmarshal(data, &varViewSelectionConfiguration)

	if err != nil {
		return err
	}

	*o = ViewSelectionConfiguration(varViewSelectionConfiguration)

	return err
}

type NullableViewSelectionConfiguration struct {
	value *ViewSelectionConfiguration
	isSet bool
}

func (v NullableViewSelectionConfiguration) Get() *ViewSelectionConfiguration {
	return v.value
}

func (v *NullableViewSelectionConfiguration) Set(val *ViewSelectionConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableViewSelectionConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableViewSelectionConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewSelectionConfiguration(val *ViewSelectionConfiguration) *NullableViewSelectionConfiguration {
	return &NullableViewSelectionConfiguration{value: val, isSet: true}
}

func (v NullableViewSelectionConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewSelectionConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
