/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RunAnalyticsGroupBy the model 'RunAnalyticsGroupBy'
type RunAnalyticsGroupBy string

// List of RunAnalyticsGroupBy
const (
	RUNANALYTICSGROUPBY_INTERACTION              RunAnalyticsGroupBy = "interaction"
	RUNANALYTICSGROUPBY_MODEL_ID                 RunAnalyticsGroupBy = "modelId"
	RUNANALYTICSGROUPBY_PROJECT                  RunAnalyticsGroupBy = "project"
	RUNANALYTICSGROUPBY_STATUS                   RunAnalyticsGroupBy = "status"
	RUNANALYTICSGROUPBY_TAGS                     RunAnalyticsGroupBy = "tags"
	RUNANALYTICSGROUPBY_ENVIRONMENT              RunAnalyticsGroupBy = "environment"
	RUNANALYTICSGROUPBY_UNKNOWN_DEFAULT_OPEN_API RunAnalyticsGroupBy = "unknown_default_open_api"
)

// All allowed values of RunAnalyticsGroupBy enum
var AllowedRunAnalyticsGroupByEnumValues = []RunAnalyticsGroupBy{
	"interaction",
	"modelId",
	"project",
	"status",
	"tags",
	"environment",
	"unknown_default_open_api",
}

func (v *RunAnalyticsGroupBy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RunAnalyticsGroupBy(value)
	for _, existing := range AllowedRunAnalyticsGroupByEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = RUNANALYTICSGROUPBY_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewRunAnalyticsGroupByFromValue returns a pointer to a valid RunAnalyticsGroupBy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRunAnalyticsGroupByFromValue(v string) (*RunAnalyticsGroupBy, error) {
	ev := RunAnalyticsGroupBy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RunAnalyticsGroupBy: valid values are %v", v, AllowedRunAnalyticsGroupByEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RunAnalyticsGroupBy) IsValid() bool {
	for _, existing := range AllowedRunAnalyticsGroupByEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RunAnalyticsGroupBy value
func (v RunAnalyticsGroupBy) Ptr() *RunAnalyticsGroupBy {
	return &v
}

type NullableRunAnalyticsGroupBy struct {
	value *RunAnalyticsGroupBy
	isSet bool
}

func (v NullableRunAnalyticsGroupBy) Get() *RunAnalyticsGroupBy {
	return v.value
}

func (v *NullableRunAnalyticsGroupBy) Set(val *RunAnalyticsGroupBy) {
	v.value = val
	v.isSet = true
}

func (v NullableRunAnalyticsGroupBy) IsSet() bool {
	return v.isSet
}

func (v *NullableRunAnalyticsGroupBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunAnalyticsGroupBy(val *RunAnalyticsGroupBy) *NullableRunAnalyticsGroupBy {
	return &NullableRunAnalyticsGroupBy{value: val, isSet: true}
}

func (v NullableRunAnalyticsGroupBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunAnalyticsGroupBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
