/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.6.0-dev.20261004.085740Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AuditAdoptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditAdoptionResponse{}

// AuditAdoptionResponse Distinct user adoption sets over two equal-duration half-open periods. Ratios use available audit history, not guaranteed historical coverage. No user identities are returned.
type AuditAdoptionResponse struct {
	Period                AuditAdoptionPeriod       `json:"period"`
	PreviousPeriod        AuditAdoptionPeriod       `json:"previous_period"`
	Resolution            string                    `json:"resolution"`
	ActiveUsers           int32                     `json:"active_users"`
	PreviousActiveUsers   int32                     `json:"previous_active_users"`
	RetainedUsers         int32                     `json:"retained_users"`
	ObservedRetention     NullableFloat32           `json:"observed_retention"`
	ReturningUserShare    NullableFloat32           `json:"returning_user_share"`
	RepeatUserShare       NullableFloat32           `json:"repeat_user_share"`
	MedianActiveDays      NullableFloat32           `json:"median_active_days"`
	ActiveProjects        NullableInt32             `json:"active_projects"`
	Timeline              []AuditAdoptionBucket     `json:"timeline"`
	ActiveDayDistribution []AuditAdoptionActiveDays `json:"active_day_distribution"`
	TopProjects           []AuditAdoptionProject    `json:"top_projects"`
	History               AuditAdoptionHistory      `json:"history"`
}

type _AuditAdoptionResponse AuditAdoptionResponse

// NewAuditAdoptionResponse instantiates a new AuditAdoptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditAdoptionResponse(period AuditAdoptionPeriod, previousPeriod AuditAdoptionPeriod, resolution string, activeUsers int32, previousActiveUsers int32, retainedUsers int32, observedRetention NullableFloat32, returningUserShare NullableFloat32, repeatUserShare NullableFloat32, medianActiveDays NullableFloat32, activeProjects NullableInt32, timeline []AuditAdoptionBucket, activeDayDistribution []AuditAdoptionActiveDays, topProjects []AuditAdoptionProject, history AuditAdoptionHistory) *AuditAdoptionResponse {
	this := AuditAdoptionResponse{}
	this.Period = period
	this.PreviousPeriod = previousPeriod
	this.Resolution = resolution
	this.ActiveUsers = activeUsers
	this.PreviousActiveUsers = previousActiveUsers
	this.RetainedUsers = retainedUsers
	this.ObservedRetention = observedRetention
	this.ReturningUserShare = returningUserShare
	this.RepeatUserShare = repeatUserShare
	this.MedianActiveDays = medianActiveDays
	this.ActiveProjects = activeProjects
	this.Timeline = timeline
	this.ActiveDayDistribution = activeDayDistribution
	this.TopProjects = topProjects
	this.History = history
	return &this
}

// NewAuditAdoptionResponseWithDefaults instantiates a new AuditAdoptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditAdoptionResponseWithDefaults() *AuditAdoptionResponse {
	this := AuditAdoptionResponse{}
	return &this
}

// GetPeriod returns the Period field value
func (o *AuditAdoptionResponse) GetPeriod() AuditAdoptionPeriod {
	if o == nil {
		var ret AuditAdoptionPeriod
		return ret
	}

	return o.Period
}

// GetPeriodOk returns a tuple with the Period field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetPeriodOk() (*AuditAdoptionPeriod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Period, true
}

// SetPeriod sets field value
func (o *AuditAdoptionResponse) SetPeriod(v AuditAdoptionPeriod) {
	o.Period = v
}

// GetPreviousPeriod returns the PreviousPeriod field value
func (o *AuditAdoptionResponse) GetPreviousPeriod() AuditAdoptionPeriod {
	if o == nil {
		var ret AuditAdoptionPeriod
		return ret
	}

	return o.PreviousPeriod
}

// GetPreviousPeriodOk returns a tuple with the PreviousPeriod field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetPreviousPeriodOk() (*AuditAdoptionPeriod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousPeriod, true
}

// SetPreviousPeriod sets field value
func (o *AuditAdoptionResponse) SetPreviousPeriod(v AuditAdoptionPeriod) {
	o.PreviousPeriod = v
}

// GetResolution returns the Resolution field value
func (o *AuditAdoptionResponse) GetResolution() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetResolutionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resolution, true
}

// SetResolution sets field value
func (o *AuditAdoptionResponse) SetResolution(v string) {
	o.Resolution = v
}

// GetActiveUsers returns the ActiveUsers field value
func (o *AuditAdoptionResponse) GetActiveUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveUsers
}

// GetActiveUsersOk returns a tuple with the ActiveUsers field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetActiveUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveUsers, true
}

// SetActiveUsers sets field value
func (o *AuditAdoptionResponse) SetActiveUsers(v int32) {
	o.ActiveUsers = v
}

// GetPreviousActiveUsers returns the PreviousActiveUsers field value
func (o *AuditAdoptionResponse) GetPreviousActiveUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PreviousActiveUsers
}

// GetPreviousActiveUsersOk returns a tuple with the PreviousActiveUsers field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetPreviousActiveUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousActiveUsers, true
}

// SetPreviousActiveUsers sets field value
func (o *AuditAdoptionResponse) SetPreviousActiveUsers(v int32) {
	o.PreviousActiveUsers = v
}

// GetRetainedUsers returns the RetainedUsers field value
func (o *AuditAdoptionResponse) GetRetainedUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetainedUsers
}

// GetRetainedUsersOk returns a tuple with the RetainedUsers field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetRetainedUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetainedUsers, true
}

// SetRetainedUsers sets field value
func (o *AuditAdoptionResponse) SetRetainedUsers(v int32) {
	o.RetainedUsers = v
}

// GetObservedRetention returns the ObservedRetention field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *AuditAdoptionResponse) GetObservedRetention() float32 {
	if o == nil || o.ObservedRetention.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ObservedRetention.Get()
}

// GetObservedRetentionOk returns a tuple with the ObservedRetention field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditAdoptionResponse) GetObservedRetentionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservedRetention.Get(), o.ObservedRetention.IsSet()
}

// SetObservedRetention sets field value
func (o *AuditAdoptionResponse) SetObservedRetention(v float32) {
	o.ObservedRetention.Set(&v)
}

// GetReturningUserShare returns the ReturningUserShare field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *AuditAdoptionResponse) GetReturningUserShare() float32 {
	if o == nil || o.ReturningUserShare.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ReturningUserShare.Get()
}

// GetReturningUserShareOk returns a tuple with the ReturningUserShare field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditAdoptionResponse) GetReturningUserShareOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturningUserShare.Get(), o.ReturningUserShare.IsSet()
}

// SetReturningUserShare sets field value
func (o *AuditAdoptionResponse) SetReturningUserShare(v float32) {
	o.ReturningUserShare.Set(&v)
}

// GetRepeatUserShare returns the RepeatUserShare field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *AuditAdoptionResponse) GetRepeatUserShare() float32 {
	if o == nil || o.RepeatUserShare.Get() == nil {
		var ret float32
		return ret
	}

	return *o.RepeatUserShare.Get()
}

// GetRepeatUserShareOk returns a tuple with the RepeatUserShare field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditAdoptionResponse) GetRepeatUserShareOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RepeatUserShare.Get(), o.RepeatUserShare.IsSet()
}

// SetRepeatUserShare sets field value
func (o *AuditAdoptionResponse) SetRepeatUserShare(v float32) {
	o.RepeatUserShare.Set(&v)
}

// GetMedianActiveDays returns the MedianActiveDays field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *AuditAdoptionResponse) GetMedianActiveDays() float32 {
	if o == nil || o.MedianActiveDays.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MedianActiveDays.Get()
}

// GetMedianActiveDaysOk returns a tuple with the MedianActiveDays field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditAdoptionResponse) GetMedianActiveDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MedianActiveDays.Get(), o.MedianActiveDays.IsSet()
}

// SetMedianActiveDays sets field value
func (o *AuditAdoptionResponse) SetMedianActiveDays(v float32) {
	o.MedianActiveDays.Set(&v)
}

// GetActiveProjects returns the ActiveProjects field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *AuditAdoptionResponse) GetActiveProjects() int32 {
	if o == nil || o.ActiveProjects.Get() == nil {
		var ret int32
		return ret
	}

	return *o.ActiveProjects.Get()
}

// GetActiveProjectsOk returns a tuple with the ActiveProjects field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditAdoptionResponse) GetActiveProjectsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveProjects.Get(), o.ActiveProjects.IsSet()
}

// SetActiveProjects sets field value
func (o *AuditAdoptionResponse) SetActiveProjects(v int32) {
	o.ActiveProjects.Set(&v)
}

// GetTimeline returns the Timeline field value
func (o *AuditAdoptionResponse) GetTimeline() []AuditAdoptionBucket {
	if o == nil {
		var ret []AuditAdoptionBucket
		return ret
	}

	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetTimelineOk() ([]AuditAdoptionBucket, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeline, true
}

// SetTimeline sets field value
func (o *AuditAdoptionResponse) SetTimeline(v []AuditAdoptionBucket) {
	o.Timeline = v
}

// GetActiveDayDistribution returns the ActiveDayDistribution field value
func (o *AuditAdoptionResponse) GetActiveDayDistribution() []AuditAdoptionActiveDays {
	if o == nil {
		var ret []AuditAdoptionActiveDays
		return ret
	}

	return o.ActiveDayDistribution
}

// GetActiveDayDistributionOk returns a tuple with the ActiveDayDistribution field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetActiveDayDistributionOk() ([]AuditAdoptionActiveDays, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveDayDistribution, true
}

// SetActiveDayDistribution sets field value
func (o *AuditAdoptionResponse) SetActiveDayDistribution(v []AuditAdoptionActiveDays) {
	o.ActiveDayDistribution = v
}

// GetTopProjects returns the TopProjects field value
func (o *AuditAdoptionResponse) GetTopProjects() []AuditAdoptionProject {
	if o == nil {
		var ret []AuditAdoptionProject
		return ret
	}

	return o.TopProjects
}

// GetTopProjectsOk returns a tuple with the TopProjects field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetTopProjectsOk() ([]AuditAdoptionProject, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopProjects, true
}

// SetTopProjects sets field value
func (o *AuditAdoptionResponse) SetTopProjects(v []AuditAdoptionProject) {
	o.TopProjects = v
}

// GetHistory returns the History field value
func (o *AuditAdoptionResponse) GetHistory() AuditAdoptionHistory {
	if o == nil {
		var ret AuditAdoptionHistory
		return ret
	}

	return o.History
}

// GetHistoryOk returns a tuple with the History field value
// and a boolean to check if the value has been set.
func (o *AuditAdoptionResponse) GetHistoryOk() (*AuditAdoptionHistory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.History, true
}

// SetHistory sets field value
func (o *AuditAdoptionResponse) SetHistory(v AuditAdoptionHistory) {
	o.History = v
}

func (o AuditAdoptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditAdoptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["period"] = o.Period
	toSerialize["previous_period"] = o.PreviousPeriod
	toSerialize["resolution"] = o.Resolution
	toSerialize["active_users"] = o.ActiveUsers
	toSerialize["previous_active_users"] = o.PreviousActiveUsers
	toSerialize["retained_users"] = o.RetainedUsers
	toSerialize["observed_retention"] = o.ObservedRetention.Get()
	toSerialize["returning_user_share"] = o.ReturningUserShare.Get()
	toSerialize["repeat_user_share"] = o.RepeatUserShare.Get()
	toSerialize["median_active_days"] = o.MedianActiveDays.Get()
	toSerialize["active_projects"] = o.ActiveProjects.Get()
	toSerialize["timeline"] = o.Timeline
	toSerialize["active_day_distribution"] = o.ActiveDayDistribution
	toSerialize["top_projects"] = o.TopProjects
	toSerialize["history"] = o.History
	return toSerialize, nil
}

func (o *AuditAdoptionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"period",
		"previous_period",
		"resolution",
		"active_users",
		"previous_active_users",
		"retained_users",
		"observed_retention",
		"returning_user_share",
		"repeat_user_share",
		"median_active_days",
		"active_projects",
		"timeline",
		"active_day_distribution",
		"top_projects",
		"history",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditAdoptionResponse := _AuditAdoptionResponse{}

	err = json.Unmarshal(data, &varAuditAdoptionResponse)

	if err != nil {
		return err
	}

	*o = AuditAdoptionResponse(varAuditAdoptionResponse)

	return err
}

type NullableAuditAdoptionResponse struct {
	value *AuditAdoptionResponse
	isSet bool
}

func (v NullableAuditAdoptionResponse) Get() *AuditAdoptionResponse {
	return v.value
}

func (v *NullableAuditAdoptionResponse) Set(val *AuditAdoptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditAdoptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditAdoptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditAdoptionResponse(val *AuditAdoptionResponse) *NullableAuditAdoptionResponse {
	return &NullableAuditAdoptionResponse{value: val, isSet: true}
}

func (v NullableAuditAdoptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditAdoptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
