/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AuditAggregationDistinctField the model 'AuditAggregationDistinctField'
type AuditAggregationDistinctField string

// List of AuditAggregationDistinctField
const (
	AUDITAGGREGATIONDISTINCTFIELD_RESOURCE_ID              AuditAggregationDistinctField = "resource_id"
	AUDITAGGREGATIONDISTINCTFIELD_REQUEST_ID               AuditAggregationDistinctField = "request_id"
	AUDITAGGREGATIONDISTINCTFIELD_UNKNOWN_DEFAULT_OPEN_API AuditAggregationDistinctField = "unknown_default_open_api"
)

// All allowed values of AuditAggregationDistinctField enum
var AllowedAuditAggregationDistinctFieldEnumValues = []AuditAggregationDistinctField{
	"resource_id",
	"request_id",
	"unknown_default_open_api",
}

func (v *AuditAggregationDistinctField) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuditAggregationDistinctField(value)
	for _, existing := range AllowedAuditAggregationDistinctFieldEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = AUDITAGGREGATIONDISTINCTFIELD_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewAuditAggregationDistinctFieldFromValue returns a pointer to a valid AuditAggregationDistinctField
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuditAggregationDistinctFieldFromValue(v string) (*AuditAggregationDistinctField, error) {
	ev := AuditAggregationDistinctField(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuditAggregationDistinctField: valid values are %v", v, AllowedAuditAggregationDistinctFieldEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuditAggregationDistinctField) IsValid() bool {
	for _, existing := range AllowedAuditAggregationDistinctFieldEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuditAggregationDistinctField value
func (v AuditAggregationDistinctField) Ptr() *AuditAggregationDistinctField {
	return &v
}

type NullableAuditAggregationDistinctField struct {
	value *AuditAggregationDistinctField
	isSet bool
}

func (v NullableAuditAggregationDistinctField) Get() *AuditAggregationDistinctField {
	return v.value
}

func (v *NullableAuditAggregationDistinctField) Set(val *AuditAggregationDistinctField) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditAggregationDistinctField) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditAggregationDistinctField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditAggregationDistinctField(val *AuditAggregationDistinctField) *NullableAuditAggregationDistinctField {
	return &NullableAuditAggregationDistinctField{value: val, isSet: true}
}

func (v NullableAuditAggregationDistinctField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditAggregationDistinctField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
