/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.6.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateAgentArtifactContentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAgentArtifactContentResponse{}

// UpdateAgentArtifactContentResponse Result of a conditional agent artifact update.
type UpdateAgentArtifactContentResponse struct {
	Path       string `json:"path"`
	Generation string `json:"generation"`
}

type _UpdateAgentArtifactContentResponse UpdateAgentArtifactContentResponse

// NewUpdateAgentArtifactContentResponse instantiates a new UpdateAgentArtifactContentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAgentArtifactContentResponse(path string, generation string) *UpdateAgentArtifactContentResponse {
	this := UpdateAgentArtifactContentResponse{}
	this.Path = path
	this.Generation = generation
	return &this
}

// NewUpdateAgentArtifactContentResponseWithDefaults instantiates a new UpdateAgentArtifactContentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAgentArtifactContentResponseWithDefaults() *UpdateAgentArtifactContentResponse {
	this := UpdateAgentArtifactContentResponse{}
	return &this
}

// GetPath returns the Path field value
func (o *UpdateAgentArtifactContentResponse) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *UpdateAgentArtifactContentResponse) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *UpdateAgentArtifactContentResponse) SetPath(v string) {
	o.Path = v
}

// GetGeneration returns the Generation field value
func (o *UpdateAgentArtifactContentResponse) GetGeneration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Generation
}

// GetGenerationOk returns a tuple with the Generation field value
// and a boolean to check if the value has been set.
func (o *UpdateAgentArtifactContentResponse) GetGenerationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Generation, true
}

// SetGeneration sets field value
func (o *UpdateAgentArtifactContentResponse) SetGeneration(v string) {
	o.Generation = v
}

func (o UpdateAgentArtifactContentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAgentArtifactContentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["generation"] = o.Generation
	return toSerialize, nil
}

func (o *UpdateAgentArtifactContentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"generation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAgentArtifactContentResponse := _UpdateAgentArtifactContentResponse{}

	err = json.Unmarshal(data, &varUpdateAgentArtifactContentResponse)

	if err != nil {
		return err
	}

	*o = UpdateAgentArtifactContentResponse(varUpdateAgentArtifactContentResponse)

	return err
}

type NullableUpdateAgentArtifactContentResponse struct {
	value *UpdateAgentArtifactContentResponse
	isSet bool
}

func (v NullableUpdateAgentArtifactContentResponse) Get() *UpdateAgentArtifactContentResponse {
	return v.value
}

func (v *NullableUpdateAgentArtifactContentResponse) Set(val *UpdateAgentArtifactContentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAgentArtifactContentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAgentArtifactContentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAgentArtifactContentResponse(val *UpdateAgentArtifactContentResponse) *NullableUpdateAgentArtifactContentResponse {
	return &NullableUpdateAgentArtifactContentResponse{value: val, isSet: true}
}

func (v NullableUpdateAgentArtifactContentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAgentArtifactContentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
