/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev.20260714.072725Z
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListWorkflowRunsPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWorkflowRunsPayload{}

// ListWorkflowRunsPayload struct for ListWorkflowRunsPayload
type ListWorkflowRunsPayload struct {
	// The document ID passed to a workflow run.
	DocumentId *string `json:"document_id,omitempty"`
	// The event name that triggered the workflow.
	EventName *string `json:"event_name,omitempty"`
	// Legacy workflow rule ID filter, when applicable.
	RuleId *string `json:"rule_id,omitempty"`
	// The start time for filtering workflow runs.
	Start *string `json:"start,omitempty"`
	// The end time for filtering workflow runs.
	End *string `json:"end,omitempty"`
	// The status of the workflow run.
	Status *string `json:"status,omitempty"`
	// search term to filter on workflow id and run id
	SearchTerm *string `json:"search_term,omitempty"`
	// The user or service account that initiated the workflow run.
	InitiatedBy *string `json:"initiated_by,omitempty"`
	// The interaction name used to filter conversations.
	Interaction *string `json:"interaction,omitempty"`
	// Lucene query string to search for the workflow runs. This is a full text search on the workflow run history.
	Query *string `json:"query,omitempty"`
	Type  *string `json:"type,omitempty"`
	// The maximum number of results to return per page.
	PageSize *float32 `json:"page_size,omitempty"`
	// The page token for Temporal pagination.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// Filter by whether the workflow has reported errors (TemporalReportedProblems).
	HasReportedErrors *bool `json:"has_reported_errors,omitempty"`
	// Filter by the activity state of the conversation (running or idle).
	ActivityState *ConversationActivityState `json:"activity_state,omitempty"`
	// Filter by whether the conversation is interactive.
	Interactive *bool `json:"interactive,omitempty"`
}

// NewListWorkflowRunsPayload instantiates a new ListWorkflowRunsPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWorkflowRunsPayload() *ListWorkflowRunsPayload {
	this := ListWorkflowRunsPayload{}
	return &this
}

// NewListWorkflowRunsPayloadWithDefaults instantiates a new ListWorkflowRunsPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWorkflowRunsPayloadWithDefaults() *ListWorkflowRunsPayload {
	this := ListWorkflowRunsPayload{}
	return &this
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId) {
		var ret string
		return ret
	}
	return *o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetDocumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentId) {
		return nil, false
	}
	return o.DocumentId, true
}

// HasDocumentId returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasDocumentId() bool {
	if o != nil && !IsNil(o.DocumentId) {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given string and assigns it to the DocumentId field.
func (o *ListWorkflowRunsPayload) SetDocumentId(v string) {
	o.DocumentId = &v
}

// GetEventName returns the EventName field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetEventName() string {
	if o == nil || IsNil(o.EventName) {
		var ret string
		return ret
	}
	return *o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetEventNameOk() (*string, bool) {
	if o == nil || IsNil(o.EventName) {
		return nil, false
	}
	return o.EventName, true
}

// HasEventName returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasEventName() bool {
	if o != nil && !IsNil(o.EventName) {
		return true
	}

	return false
}

// SetEventName gets a reference to the given string and assigns it to the EventName field.
func (o *ListWorkflowRunsPayload) SetEventName(v string) {
	o.EventName = &v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *ListWorkflowRunsPayload) SetRuleId(v string) {
	o.RuleId = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *ListWorkflowRunsPayload) SetStart(v string) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *ListWorkflowRunsPayload) SetEnd(v string) {
	o.End = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListWorkflowRunsPayload) SetStatus(v string) {
	o.Status = &v
}

// GetSearchTerm returns the SearchTerm field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetSearchTerm() string {
	if o == nil || IsNil(o.SearchTerm) {
		var ret string
		return ret
	}
	return *o.SearchTerm
}

// GetSearchTermOk returns a tuple with the SearchTerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetSearchTermOk() (*string, bool) {
	if o == nil || IsNil(o.SearchTerm) {
		return nil, false
	}
	return o.SearchTerm, true
}

// HasSearchTerm returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasSearchTerm() bool {
	if o != nil && !IsNil(o.SearchTerm) {
		return true
	}

	return false
}

// SetSearchTerm gets a reference to the given string and assigns it to the SearchTerm field.
func (o *ListWorkflowRunsPayload) SetSearchTerm(v string) {
	o.SearchTerm = &v
}

// GetInitiatedBy returns the InitiatedBy field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetInitiatedBy() string {
	if o == nil || IsNil(o.InitiatedBy) {
		var ret string
		return ret
	}
	return *o.InitiatedBy
}

// GetInitiatedByOk returns a tuple with the InitiatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetInitiatedByOk() (*string, bool) {
	if o == nil || IsNil(o.InitiatedBy) {
		return nil, false
	}
	return o.InitiatedBy, true
}

// HasInitiatedBy returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasInitiatedBy() bool {
	if o != nil && !IsNil(o.InitiatedBy) {
		return true
	}

	return false
}

// SetInitiatedBy gets a reference to the given string and assigns it to the InitiatedBy field.
func (o *ListWorkflowRunsPayload) SetInitiatedBy(v string) {
	o.InitiatedBy = &v
}

// GetInteraction returns the Interaction field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetInteraction() string {
	if o == nil || IsNil(o.Interaction) {
		var ret string
		return ret
	}
	return *o.Interaction
}

// GetInteractionOk returns a tuple with the Interaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetInteractionOk() (*string, bool) {
	if o == nil || IsNil(o.Interaction) {
		return nil, false
	}
	return o.Interaction, true
}

// HasInteraction returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasInteraction() bool {
	if o != nil && !IsNil(o.Interaction) {
		return true
	}

	return false
}

// SetInteraction gets a reference to the given string and assigns it to the Interaction field.
func (o *ListWorkflowRunsPayload) SetInteraction(v string) {
	o.Interaction = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *ListWorkflowRunsPayload) SetQuery(v string) {
	o.Query = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ListWorkflowRunsPayload) SetType(v string) {
	o.Type = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetPageSize() float32 {
	if o == nil || IsNil(o.PageSize) {
		var ret float32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetPageSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given float32 and assigns it to the PageSize field.
func (o *ListWorkflowRunsPayload) SetPageSize(v float32) {
	o.PageSize = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListWorkflowRunsPayload) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetHasReportedErrors returns the HasReportedErrors field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetHasReportedErrors() bool {
	if o == nil || IsNil(o.HasReportedErrors) {
		var ret bool
		return ret
	}
	return *o.HasReportedErrors
}

// GetHasReportedErrorsOk returns a tuple with the HasReportedErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetHasReportedErrorsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasReportedErrors) {
		return nil, false
	}
	return o.HasReportedErrors, true
}

// HasHasReportedErrors returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasHasReportedErrors() bool {
	if o != nil && !IsNil(o.HasReportedErrors) {
		return true
	}

	return false
}

// SetHasReportedErrors gets a reference to the given bool and assigns it to the HasReportedErrors field.
func (o *ListWorkflowRunsPayload) SetHasReportedErrors(v bool) {
	o.HasReportedErrors = &v
}

// GetActivityState returns the ActivityState field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetActivityState() ConversationActivityState {
	if o == nil || IsNil(o.ActivityState) {
		var ret ConversationActivityState
		return ret
	}
	return *o.ActivityState
}

// GetActivityStateOk returns a tuple with the ActivityState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetActivityStateOk() (*ConversationActivityState, bool) {
	if o == nil || IsNil(o.ActivityState) {
		return nil, false
	}
	return o.ActivityState, true
}

// HasActivityState returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasActivityState() bool {
	if o != nil && !IsNil(o.ActivityState) {
		return true
	}

	return false
}

// SetActivityState gets a reference to the given ConversationActivityState and assigns it to the ActivityState field.
func (o *ListWorkflowRunsPayload) SetActivityState(v ConversationActivityState) {
	o.ActivityState = &v
}

// GetInteractive returns the Interactive field value if set, zero value otherwise.
func (o *ListWorkflowRunsPayload) GetInteractive() bool {
	if o == nil || IsNil(o.Interactive) {
		var ret bool
		return ret
	}
	return *o.Interactive
}

// GetInteractiveOk returns a tuple with the Interactive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkflowRunsPayload) GetInteractiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Interactive) {
		return nil, false
	}
	return o.Interactive, true
}

// HasInteractive returns a boolean if a field has been set.
func (o *ListWorkflowRunsPayload) HasInteractive() bool {
	if o != nil && !IsNil(o.Interactive) {
		return true
	}

	return false
}

// SetInteractive gets a reference to the given bool and assigns it to the Interactive field.
func (o *ListWorkflowRunsPayload) SetInteractive(v bool) {
	o.Interactive = &v
}

func (o ListWorkflowRunsPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWorkflowRunsPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocumentId) {
		toSerialize["document_id"] = o.DocumentId
	}
	if !IsNil(o.EventName) {
		toSerialize["event_name"] = o.EventName
	}
	if !IsNil(o.RuleId) {
		toSerialize["rule_id"] = o.RuleId
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SearchTerm) {
		toSerialize["search_term"] = o.SearchTerm
	}
	if !IsNil(o.InitiatedBy) {
		toSerialize["initiated_by"] = o.InitiatedBy
	}
	if !IsNil(o.Interaction) {
		toSerialize["interaction"] = o.Interaction
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	if !IsNil(o.HasReportedErrors) {
		toSerialize["has_reported_errors"] = o.HasReportedErrors
	}
	if !IsNil(o.ActivityState) {
		toSerialize["activity_state"] = o.ActivityState
	}
	if !IsNil(o.Interactive) {
		toSerialize["interactive"] = o.Interactive
	}
	return toSerialize, nil
}

type NullableListWorkflowRunsPayload struct {
	value *ListWorkflowRunsPayload
	isSet bool
}

func (v NullableListWorkflowRunsPayload) Get() *ListWorkflowRunsPayload {
	return v.value
}

func (v *NullableListWorkflowRunsPayload) Set(val *ListWorkflowRunsPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableListWorkflowRunsPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableListWorkflowRunsPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWorkflowRunsPayload(val *ListWorkflowRunsPayload) *NullableListWorkflowRunsPayload {
	return &NullableListWorkflowRunsPayload{value: val, isSet: true}
}

func (v NullableListWorkflowRunsPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWorkflowRunsPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
