/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the WorkflowRunEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowRunEvent{}

// WorkflowRunEvent struct for WorkflowRunEvent
type WorkflowRunEvent struct {
	EventId              float32                        `json:"event_id"`
	EventTime            NullableString                 `json:"event_time"`
	EventType            string                         `json:"event_type"`
	TaskId               *string                        `json:"task_id,omitempty"`
	Attempt              float32                        `json:"attempt"`
	Activity             *WorkflowRunEventActivity      `json:"activity,omitempty"`
	ChildWorkflow        *WorkflowRunEventChildWorkflow `json:"childWorkflow,omitempty"`
	Signal               *SignalEventProperties         `json:"signal,omitempty"`
	Timer                *WorkflowRunEventTimer         `json:"timer,omitempty"`
	Error                *EventError                    `json:"error,omitempty"`
	Result               interface{}                    `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowRunEvent WorkflowRunEvent

// NewWorkflowRunEvent instantiates a new WorkflowRunEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunEvent(eventId float32, eventTime NullableString, eventType string, attempt float32) *WorkflowRunEvent {
	this := WorkflowRunEvent{}
	this.EventId = eventId
	this.EventTime = eventTime
	this.EventType = eventType
	this.Attempt = attempt
	return &this
}

// NewWorkflowRunEventWithDefaults instantiates a new WorkflowRunEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunEventWithDefaults() *WorkflowRunEvent {
	this := WorkflowRunEvent{}
	return &this
}

// GetEventId returns the EventId field value
func (o *WorkflowRunEvent) GetEventId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetEventIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *WorkflowRunEvent) SetEventId(v float32) {
	o.EventId = v
}

// GetEventTime returns the EventTime field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkflowRunEvent) GetEventTime() string {
	if o == nil || o.EventTime.Get() == nil {
		var ret string
		return ret
	}

	return *o.EventTime.Get()
}

// GetEventTimeOk returns a tuple with the EventTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowRunEvent) GetEventTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTime.Get(), o.EventTime.IsSet()
}

// SetEventTime sets field value
func (o *WorkflowRunEvent) SetEventTime(v string) {
	o.EventTime.Set(&v)
}

// GetEventType returns the EventType field value
func (o *WorkflowRunEvent) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *WorkflowRunEvent) SetEventType(v string) {
	o.EventType = v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *WorkflowRunEvent) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *WorkflowRunEvent) SetTaskId(v string) {
	o.TaskId = &v
}

// GetAttempt returns the Attempt field value
func (o *WorkflowRunEvent) GetAttempt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetAttemptOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempt, true
}

// SetAttempt sets field value
func (o *WorkflowRunEvent) SetAttempt(v float32) {
	o.Attempt = v
}

// GetActivity returns the Activity field value if set, zero value otherwise.
func (o *WorkflowRunEvent) GetActivity() WorkflowRunEventActivity {
	if o == nil || IsNil(o.Activity) {
		var ret WorkflowRunEventActivity
		return ret
	}
	return *o.Activity
}

// GetActivityOk returns a tuple with the Activity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetActivityOk() (*WorkflowRunEventActivity, bool) {
	if o == nil || IsNil(o.Activity) {
		return nil, false
	}
	return o.Activity, true
}

// HasActivity returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasActivity() bool {
	if o != nil && !IsNil(o.Activity) {
		return true
	}

	return false
}

// SetActivity gets a reference to the given WorkflowRunEventActivity and assigns it to the Activity field.
func (o *WorkflowRunEvent) SetActivity(v WorkflowRunEventActivity) {
	o.Activity = &v
}

// GetChildWorkflow returns the ChildWorkflow field value if set, zero value otherwise.
func (o *WorkflowRunEvent) GetChildWorkflow() WorkflowRunEventChildWorkflow {
	if o == nil || IsNil(o.ChildWorkflow) {
		var ret WorkflowRunEventChildWorkflow
		return ret
	}
	return *o.ChildWorkflow
}

// GetChildWorkflowOk returns a tuple with the ChildWorkflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetChildWorkflowOk() (*WorkflowRunEventChildWorkflow, bool) {
	if o == nil || IsNil(o.ChildWorkflow) {
		return nil, false
	}
	return o.ChildWorkflow, true
}

// HasChildWorkflow returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasChildWorkflow() bool {
	if o != nil && !IsNil(o.ChildWorkflow) {
		return true
	}

	return false
}

// SetChildWorkflow gets a reference to the given WorkflowRunEventChildWorkflow and assigns it to the ChildWorkflow field.
func (o *WorkflowRunEvent) SetChildWorkflow(v WorkflowRunEventChildWorkflow) {
	o.ChildWorkflow = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *WorkflowRunEvent) GetSignal() SignalEventProperties {
	if o == nil || IsNil(o.Signal) {
		var ret SignalEventProperties
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetSignalOk() (*SignalEventProperties, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given SignalEventProperties and assigns it to the Signal field.
func (o *WorkflowRunEvent) SetSignal(v SignalEventProperties) {
	o.Signal = &v
}

// GetTimer returns the Timer field value if set, zero value otherwise.
func (o *WorkflowRunEvent) GetTimer() WorkflowRunEventTimer {
	if o == nil || IsNil(o.Timer) {
		var ret WorkflowRunEventTimer
		return ret
	}
	return *o.Timer
}

// GetTimerOk returns a tuple with the Timer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetTimerOk() (*WorkflowRunEventTimer, bool) {
	if o == nil || IsNil(o.Timer) {
		return nil, false
	}
	return o.Timer, true
}

// HasTimer returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasTimer() bool {
	if o != nil && !IsNil(o.Timer) {
		return true
	}

	return false
}

// SetTimer gets a reference to the given WorkflowRunEventTimer and assigns it to the Timer field.
func (o *WorkflowRunEvent) SetTimer(v WorkflowRunEventTimer) {
	o.Timer = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WorkflowRunEvent) GetError() EventError {
	if o == nil || IsNil(o.Error) {
		var ret EventError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunEvent) GetErrorOk() (*EventError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given EventError and assigns it to the Error field.
func (o *WorkflowRunEvent) SetError(v EventError) {
	o.Error = &v
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowRunEvent) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowRunEvent) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *WorkflowRunEvent) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given interface{} and assigns it to the Result field.
func (o *WorkflowRunEvent) SetResult(v interface{}) {
	o.Result = v
}

func (o WorkflowRunEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowRunEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["event_time"] = o.EventTime.Get()
	toSerialize["event_type"] = o.EventType
	if !IsNil(o.TaskId) {
		toSerialize["task_id"] = o.TaskId
	}
	toSerialize["attempt"] = o.Attempt
	if !IsNil(o.Activity) {
		toSerialize["activity"] = o.Activity
	}
	if !IsNil(o.ChildWorkflow) {
		toSerialize["childWorkflow"] = o.ChildWorkflow
	}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}
	if !IsNil(o.Timer) {
		toSerialize["timer"] = o.Timer
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowRunEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"event_time",
		"event_type",
		"attempt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowRunEvent := _WorkflowRunEvent{}

	err = json.Unmarshal(data, &varWorkflowRunEvent)

	if err != nil {
		return err
	}

	*o = WorkflowRunEvent(varWorkflowRunEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "event_time")
		delete(additionalProperties, "event_type")
		delete(additionalProperties, "task_id")
		delete(additionalProperties, "attempt")
		delete(additionalProperties, "activity")
		delete(additionalProperties, "childWorkflow")
		delete(additionalProperties, "signal")
		delete(additionalProperties, "timer")
		delete(additionalProperties, "error")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowRunEvent struct {
	value *WorkflowRunEvent
	isSet bool
}

func (v NullableWorkflowRunEvent) Get() *WorkflowRunEvent {
	return v.value
}

func (v *NullableWorkflowRunEvent) Set(val *WorkflowRunEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunEvent(val *WorkflowRunEvent) *NullableWorkflowRunEvent {
	return &NullableWorkflowRunEvent{value: val, isSet: true}
}

func (v NullableWorkflowRunEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
