/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DataStoreItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataStoreItem{}

// DataStoreItem Summary view of a data store (for listings).
type DataStoreItem struct {
	// Unique identifier for the object
	Id string `json:"id"`
	// Human-readable name or title
	Name string `json:"name"`
	// Optional detailed description of the object
	Description *string `json:"description,omitempty"`
	// Tags for organization
	Tags []string `json:"tags"`
	// Identifier of the user who last modified the object
	UpdatedBy string `json:"updated_by"`
	// Identifier of the user who created the object
	CreatedBy string `json:"created_by"`
	// ISO timestamp of when the object was created
	CreatedAt string `json:"created_at"`
	// ISO timestamp of when the object was last updated
	UpdatedAt string `json:"updated_at"`
	// Current status
	Status DataStoreStatus `json:"status"`
	// Current schema version
	SchemaVersion string `json:"schema_version"`
	// Number of tables
	TableCount float32 `json:"table_count"`
	// Total rows across all tables
	TotalRows float32 `json:"total_rows"`
	// Storage size in bytes
	StorageBytes float32 `json:"storage_bytes"`
	// Last import timestamp
	LastImportAt *string `json:"last_import_at,omitempty"`
	// Number of versions stored
	VersionCount float32 `json:"version_count"`
}

type _DataStoreItem DataStoreItem

// NewDataStoreItem instantiates a new DataStoreItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataStoreItem(id string, name string, tags []string, updatedBy string, createdBy string, createdAt string, updatedAt string, status DataStoreStatus, schemaVersion string, tableCount float32, totalRows float32, storageBytes float32, versionCount float32) *DataStoreItem {
	this := DataStoreItem{}
	this.Id = id
	this.Name = name
	this.Tags = tags
	this.UpdatedBy = updatedBy
	this.CreatedBy = createdBy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Status = status
	this.SchemaVersion = schemaVersion
	this.TableCount = tableCount
	this.TotalRows = totalRows
	this.StorageBytes = storageBytes
	this.VersionCount = versionCount
	return &this
}

// NewDataStoreItemWithDefaults instantiates a new DataStoreItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataStoreItemWithDefaults() *DataStoreItem {
	this := DataStoreItem{}
	return &this
}

// GetId returns the Id field value
func (o *DataStoreItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataStoreItem) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataStoreItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataStoreItem) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DataStoreItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DataStoreItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DataStoreItem) SetDescription(v string) {
	o.Description = &v
}

// GetTags returns the Tags field value
func (o *DataStoreItem) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *DataStoreItem) SetTags(v []string) {
	o.Tags = v
}

// GetUpdatedBy returns the UpdatedBy field value
func (o *DataStoreItem) GetUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// SetUpdatedBy sets field value
func (o *DataStoreItem) SetUpdatedBy(v string) {
	o.UpdatedBy = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *DataStoreItem) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *DataStoreItem) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DataStoreItem) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DataStoreItem) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DataStoreItem) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DataStoreItem) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetStatus returns the Status field value
func (o *DataStoreItem) GetStatus() DataStoreStatus {
	if o == nil {
		var ret DataStoreStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetStatusOk() (*DataStoreStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DataStoreItem) SetStatus(v DataStoreStatus) {
	o.Status = v
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *DataStoreItem) GetSchemaVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetSchemaVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *DataStoreItem) SetSchemaVersion(v string) {
	o.SchemaVersion = v
}

// GetTableCount returns the TableCount field value
func (o *DataStoreItem) GetTableCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TableCount
}

// GetTableCountOk returns a tuple with the TableCount field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetTableCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableCount, true
}

// SetTableCount sets field value
func (o *DataStoreItem) SetTableCount(v float32) {
	o.TableCount = v
}

// GetTotalRows returns the TotalRows field value
func (o *DataStoreItem) GetTotalRows() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalRows
}

// GetTotalRowsOk returns a tuple with the TotalRows field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetTotalRowsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRows, true
}

// SetTotalRows sets field value
func (o *DataStoreItem) SetTotalRows(v float32) {
	o.TotalRows = v
}

// GetStorageBytes returns the StorageBytes field value
func (o *DataStoreItem) GetStorageBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StorageBytes
}

// GetStorageBytesOk returns a tuple with the StorageBytes field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetStorageBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageBytes, true
}

// SetStorageBytes sets field value
func (o *DataStoreItem) SetStorageBytes(v float32) {
	o.StorageBytes = v
}

// GetLastImportAt returns the LastImportAt field value if set, zero value otherwise.
func (o *DataStoreItem) GetLastImportAt() string {
	if o == nil || IsNil(o.LastImportAt) {
		var ret string
		return ret
	}
	return *o.LastImportAt
}

// GetLastImportAtOk returns a tuple with the LastImportAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetLastImportAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastImportAt) {
		return nil, false
	}
	return o.LastImportAt, true
}

// HasLastImportAt returns a boolean if a field has been set.
func (o *DataStoreItem) HasLastImportAt() bool {
	if o != nil && !IsNil(o.LastImportAt) {
		return true
	}

	return false
}

// SetLastImportAt gets a reference to the given string and assigns it to the LastImportAt field.
func (o *DataStoreItem) SetLastImportAt(v string) {
	o.LastImportAt = &v
}

// GetVersionCount returns the VersionCount field value
func (o *DataStoreItem) GetVersionCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.VersionCount
}

// GetVersionCountOk returns a tuple with the VersionCount field value
// and a boolean to check if the value has been set.
func (o *DataStoreItem) GetVersionCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionCount, true
}

// SetVersionCount sets field value
func (o *DataStoreItem) SetVersionCount(v float32) {
	o.VersionCount = v
}

func (o DataStoreItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataStoreItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["tags"] = o.Tags
	toSerialize["updated_by"] = o.UpdatedBy
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["status"] = o.Status
	toSerialize["schema_version"] = o.SchemaVersion
	toSerialize["table_count"] = o.TableCount
	toSerialize["total_rows"] = o.TotalRows
	toSerialize["storage_bytes"] = o.StorageBytes
	if !IsNil(o.LastImportAt) {
		toSerialize["last_import_at"] = o.LastImportAt
	}
	toSerialize["version_count"] = o.VersionCount
	return toSerialize, nil
}

func (o *DataStoreItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"tags",
		"updated_by",
		"created_by",
		"created_at",
		"updated_at",
		"status",
		"schema_version",
		"table_count",
		"total_rows",
		"storage_bytes",
		"version_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataStoreItem := _DataStoreItem{}

	err = json.Unmarshal(data, &varDataStoreItem)

	if err != nil {
		return err
	}

	*o = DataStoreItem(varDataStoreItem)

	return err
}

type NullableDataStoreItem struct {
	value *DataStoreItem
	isSet bool
}

func (v NullableDataStoreItem) Get() *DataStoreItem {
	return v.value
}

func (v *NullableDataStoreItem) Set(val *DataStoreItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDataStoreItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDataStoreItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataStoreItem(val *DataStoreItem) *NullableDataStoreItem {
	return &NullableDataStoreItem{value: val, isSet: true}
}

func (v NullableDataStoreItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataStoreItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
