/*
Vertesia API

The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.

API version: 1.5.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ProjectPluginsUpdatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectPluginsUpdatePayload{}

// ProjectPluginsUpdatePayload struct for ProjectPluginsUpdatePayload
type ProjectPluginsUpdatePayload struct {
	Plugins []string `json:"plugins"`
}

type _ProjectPluginsUpdatePayload ProjectPluginsUpdatePayload

// NewProjectPluginsUpdatePayload instantiates a new ProjectPluginsUpdatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectPluginsUpdatePayload(plugins []string) *ProjectPluginsUpdatePayload {
	this := ProjectPluginsUpdatePayload{}
	this.Plugins = plugins
	return &this
}

// NewProjectPluginsUpdatePayloadWithDefaults instantiates a new ProjectPluginsUpdatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectPluginsUpdatePayloadWithDefaults() *ProjectPluginsUpdatePayload {
	this := ProjectPluginsUpdatePayload{}
	return &this
}

// GetPlugins returns the Plugins field value
func (o *ProjectPluginsUpdatePayload) GetPlugins() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value
// and a boolean to check if the value has been set.
func (o *ProjectPluginsUpdatePayload) GetPluginsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Plugins, true
}

// SetPlugins sets field value
func (o *ProjectPluginsUpdatePayload) SetPlugins(v []string) {
	o.Plugins = v
}

func (o ProjectPluginsUpdatePayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectPluginsUpdatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plugins"] = o.Plugins
	return toSerialize, nil
}

func (o *ProjectPluginsUpdatePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plugins",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectPluginsUpdatePayload := _ProjectPluginsUpdatePayload{}

	err = json.Unmarshal(data, &varProjectPluginsUpdatePayload)

	if err != nil {
		return err
	}

	*o = ProjectPluginsUpdatePayload(varProjectPluginsUpdatePayload)

	return err
}

type NullableProjectPluginsUpdatePayload struct {
	value *ProjectPluginsUpdatePayload
	isSet bool
}

func (v NullableProjectPluginsUpdatePayload) Get() *ProjectPluginsUpdatePayload {
	return v.value
}

func (v *NullableProjectPluginsUpdatePayload) Set(val *ProjectPluginsUpdatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectPluginsUpdatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectPluginsUpdatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectPluginsUpdatePayload(val *ProjectPluginsUpdatePayload) *NullableProjectPluginsUpdatePayload {
	return &NullableProjectPluginsUpdatePayload{value: val, isSet: true}
}

func (v NullableProjectPluginsUpdatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectPluginsUpdatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
